-- 043 · Deck-E's transcript history — what was said, what ran, and on which build.
--
-- ══════════════════════════════════════════════════════════════════════════════
-- WHY THIS EXISTS, IN THE OWNER'S WORDS
-- ══════════════════════════════════════════════════════════════════════════════
--
--   "First it's just helpful. But second, I think fixing things and improving
--    the agent will be greatly helped by having a full record of all my chats,
--    which tools were called. Should probably have each chat transcript record
--    say what was the latest PR it's immediately after so we can easily spot
--    regressions."
--
-- So this is two products in one table set. A reader wants to find a
-- conversation again; a maintainer wants to answer "did this get worse, and
-- when". The second is the demanding one and it is what the columns are shaped
-- for — a history that cannot be correlated with a build is an anecdote.
--
-- ══════════════════════════════════════════════════════════════════════════════
-- THE BUILD STAMP IS PER TURN, NOT PER CONVERSATION
-- ══════════════════════════════════════════════════════════════════════════════
--
-- A conversation can outlive a deploy. Ask something at 14:00, ship at 14:05,
-- ask a follow-up at 14:10, and a conversation-level stamp would attribute both
-- turns to whichever build happened to be recorded first — which is precisely
-- the case somebody is investigating when they go looking. Stamping the TURN
-- costs two small columns and makes "it broke somewhere between #78 and #81" a
-- query instead of a guess.
--
-- `build_pr` is an integer because it is the thing being compared and ordered.
-- It comes from the squash-merge subject on `main` — this repository's
-- convention is `Title (#78)` — and it is NULL for a preview build, a local
-- run, or any deploy whose commit subject carries no PR reference. NULL means
-- "not attributable", which is honest; zero would sort as a real value.
--
-- `build_sha` is the exact commit and is never null on a Vercel deploy. It is
-- the fallback identity when `build_pr` is NULL and the tiebreaker when two
-- deploys share a PR (a re-deploy of the same merge).
--
-- ══════════════════════════════════════════════════════════════════════════════
-- WHAT A "TURN" IS HERE, WHICH IS NOT WHAT `decke_usage` MEANS BY IT
-- ══════════════════════════════════════════════════════════════════════════════
--
-- `decke_usage` counts BILLED MODEL REQUESTS, so one sentence from a reader can
-- cost four. That is the honest unit for money and the wrong unit for a
-- transcript: nobody reading their own history wants four rows for one
-- question.
--
-- A row here is ONE EXCHANGE — what they typed and everything that came back
-- before they could type again, tool calls included. The two definitions are
-- deliberately different and neither is wrong; they are answering different
-- questions, and a comment saying so is cheaper than the afternoon somebody
-- would otherwise spend reconciling the counts.
--
-- ══════════════════════════════════════════════════════════════════════════════
-- TOOLS AS JSONB, AND WHY NOT A THIRD TABLE
-- ══════════════════════════════════════════════════════════════════════════════
--
-- A `decke_turn_tool` table would be the textbook shape and would earn its keep
-- if tools were queried across turns independently. They are not: every question
-- this exists to answer starts from a turn — "what ran during this exchange",
-- "which turns called `plan_deck` and failed". Postgres indexes jsonb well
-- enough for both, and the write path stays one INSERT, which matters because
-- it runs on the hot path of every exchange.
--
-- The shape is fixed and documented rather than free-form: an array of
-- `{ name, phase, title, summary }`. `phase` is the chip's own word — `ok`,
-- `partial`, `error`, `declined` — so a regression hunt can ask "when did this
-- tool start coming back `error`" without parsing prose.

CREATE TABLE IF NOT EXISTS decke_conversation (
  -- Generated by the CLIENT, so every turn of one exchange can be attributed to
  -- the same conversation without a round trip to claim an id first. It is a
  -- uuid and it is namespaced by `user_id` in every query, so a guessed value
  -- reaches nothing.
  id          uuid        PRIMARY KEY,
  user_id     uuid        NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  -- The first thing they asked, trimmed. A title somebody wrote beats a title
  -- somebody generated, and the first question is the closest thing to one.
  title       text        NOT NULL DEFAULT '',
  started_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  turns       integer     NOT NULL DEFAULT 0,
  CONSTRAINT decke_conversation_turns_non_negative CHECK (turns >= 0)
);

-- The dropdown's query: this user's conversations, newest activity first.
CREATE INDEX IF NOT EXISTS decke_conversation_user_idx
  ON decke_conversation (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS decke_turn (
  id              bigserial   PRIMARY KEY,
  conversation_id uuid        NOT NULL REFERENCES decke_conversation(id) ON DELETE CASCADE,
  -- Denormalised from the conversation ON PURPOSE. Every read is scoped to the
  -- caller, and RLS below is per-row: without this, a policy on turns would
  -- have to join to the conversation on every single row.
  user_id         uuid        NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  -- Position in the conversation, from the client's own count.
  seq             integer     NOT NULL,
  asked           text        NOT NULL DEFAULT '',
  answered        text        NOT NULL DEFAULT '',
  -- `[{ name, phase, title, summary }]`. See the header.
  tools           jsonb       NOT NULL DEFAULT '[]'::jsonb,
  -- The PR this build is immediately after, from the squash-merge subject.
  -- NULL for a preview, a local run, or a commit with no PR reference.
  build_pr        integer,
  build_sha       text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT decke_turn_seq_non_negative CHECK (seq >= 0),
  -- A RETRY MUST NOT DOUBLE-WRITE. The client posts this after a turn settles,
  -- and a flaky network turns one exchange into two identical rows — which is
  -- the failure that makes a history stop being trustworthy exactly when
  -- somebody is counting on it. Re-posting the same position is an upsert.
  CONSTRAINT decke_turn_unique_position UNIQUE (conversation_id, seq)
);

-- "Show me this conversation", in order.
CREATE INDEX IF NOT EXISTS decke_turn_conversation_idx
  ON decke_turn (conversation_id, seq);

-- THE REGRESSION QUERY, which is the whole second half of the point: every turn
-- on a given build, newest first. Without this, "what changed after #78" is a
-- full scan of every turn anybody has ever taken.
CREATE INDEX IF NOT EXISTS decke_turn_build_idx
  ON decke_turn (build_pr DESC NULLS LAST, created_at DESC);

-- "Which turns called this tool, and how did it come back." A GIN index over
-- the array makes a containment query — `tools @> '[{"name":"plan_deck"}]'` —
-- an index scan instead of a scan of every row's jsonb.
CREATE INDEX IF NOT EXISTS decke_turn_tools_idx
  ON decke_turn USING GIN (tools jsonb_path_ops);
