#!/usr/bin/env node
/**
 * Snapshot printed frames for scripted cards into src/cards/frames.json from
 * the public DeckPal catalog (GET https://deckpal.app/api/cards/:id). The
 * snapshot (src/cards/frames.ts, generated) keeps the engine's tests pure (no network, no DB in CI) and is the
 * reference the text round-trip check compares scripts against.
 *
 *   node scripts/fetch-frames.mjs                # refresh every id already in the file + every script id
 *   node scripts/fetch-frames.mjs me05-039 ...   # add these ids
 *
 * DECKPAL_API overrides the base URL (e.g. a local API).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'cards', 'frames.ts');
const base = process.env.DECKPAL_API ?? 'https://deckpal.app/api';
const HEAD = [
  '// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.',
  "import type { CardFrame } from '../types.js';",
  '',
  'export const FRAMES: Record<string, CardFrame> = ',
].join('\n');
const src = readFileSync(out, 'utf8');
const marker = 'CardFrame> = ';
const frames = JSON.parse(src.slice(src.indexOf(marker) + marker.length).replace(/;\s*$/, ''));

// Ids referenced by scripts: `id: 'xxx'` in src/cards/scripts/*.ts
import { readdirSync } from 'node:fs';
const sdir = join(here, '..', 'src', 'cards', 'scripts');
const scriptIds = new Set();
for (const f of readdirSync(sdir)) {
  if (!f.endsWith('.ts')) continue;
  for (const m of readFileSync(join(sdir, f), 'utf8').matchAll(/\bid:\s*'([^']+)'/g)) scriptIds.add(m[1]);
}
const ids = process.argv.length > 2 ? process.argv.slice(2) : [...new Set([...Object.keys(frames), ...scriptIds])];

const KEEP = ['cardId', 'name', 'category', 'hp', 'stage', 'suffix', 'evolvesFrom', 'trainerType', 'energyType', 'retreat', 'types', 'effect', 'regulationMark', 'attacks', 'abilities', 'weaknesses', 'resistances'];
let n = 0;
for (const id of ids) {
  const r = await fetch(`${base}/cards/${encodeURIComponent(id)}`);
  if (!r.ok) {
    console.error(`${id}: HTTP ${r.status}`);
    process.exitCode = 1;
    continue;
  }
  const { card } = await r.json();
  const f = {};
  for (const k of KEEP) f[k] = card[k] ?? null;
  frames[id] = f;
  n++;
}
const sorted = Object.fromEntries(Object.keys(frames).sort().map((k) => [k, frames[k]]));
writeFileSync(out, `${HEAD}${JSON.stringify(sorted, null, 1)};\n`);
console.log(`frames: ${n} fetched, ${Object.keys(sorted).length} total → ${out}`);
