/** Guidance loaded when results should become a justified deck version. */
export const DECK_ITERATE_TEXT = `Your goal is a next version whose changes are supported by results and preserved in the version history.

Read \`deck_history\` for the version line — each version's record and why it changed; it holds no cards, so the list comes from \`decks\` with \`include: ["cards"]\`. Then read \`battle_logs\` for the current \`version\`, opening the losses that matter by \`log_id\` because list rows cut notes to 40 characters. Say the headline in one line before you propose. Show record by opposing archetype and be explicit about sample size: two losses can raise a question, not prove a matchup is bad. Keep observations from an older version attached to that older list.

Look for repeated evidence in those notes: a card dead in several losses, the same missing out, repeated setup trouble, or “wished I had X” more than once. Propose at most two changes at a time, normally one card in and one card out for each idea. Cite the evidence in ordinary language — “dead in four of six losses” or “you wished for it three times” — and say what result would support keeping the experiment. Do not solve a noisy sample with a wholesale rewrite.

Once the reader agrees, call \`save_deck\` with \`mode: "edit"\`, its \`deck_id\` and the **complete** list with the change applied — \`cards\` replaces the whole deck, it is not a diff — plus a \`version_note\` that says why the change was made and cites the evidence; its reply names the version. Show the change as in and out lines, not \`showDeck\`, whose Save makes a separate deck. To build off v1, read it with \`deck_history\` (\`version: 1\`), edit that list and save it the same way; \`revert_to\` brings an older list back unchanged, and its strategy guide too unless \`include_strategy: false\`. A deck's history is a line, not a tree.

Done means a new version is saved with a meaningful \`version_note\` once the reader agrees, the reader knows which version it became, and you have named what to watch in the next games. Keep observations separate from proposals, and **END with at most two concrete next steps, one line each.** Never present a diff without naming the comparison version, silently edit without a version reason, or promise that a small sample proves the change.`
