// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "base1-101": {
  "cardId": "base1-101",
  "name": "Psychic Energy",
  "category": "Energy",
  "hp": null,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": "Normal",
  "retreat": null,
  "types": [],
  "effect": null,
  "regulationMark": null,
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me01-104": {
  "cardId": "me01-104",
  "name": "Mega Kangaskhan ex",
  "category": "Pokemon",
  "hp": 300,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Rapid-Fire Combo",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "200+",
    "effect": "Flip a coin until you get tails. This attack does 50 more damage for each heads."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Run Errand",
    "effect": "Once during your turn, if this Pokémon is in the Active Spot, you may use this Ability. Draw 2 cards. You can't use more than 1 Run Errand Ability each turn."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me01-114": {
  "cardId": "me01-114",
  "name": "Boss's Orders",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Switch in 1 of your opponent's Benched Pokémon to the Active Spot.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me01-119": {
  "cardId": "me01-119",
  "name": "Lillie's Determination",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Shuffle your hand into your deck. Then, draw 6 cards. If you have exactly 6 Prize cards remaining, draw 8 cards instead.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me01-130": {
  "cardId": "me01-130",
  "name": "Switch",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Switch your Active Pokémon with 1 of your Benched Pokémon.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me01-131": {
  "cardId": "me01-131",
  "name": "Ultra Ball",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "You can use this card only if you discard 2 other cards from your hand.\n\nSearch your deck for a Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02-094": {
  "cardId": "me02-094",
  "name": "Wondrous Patch",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Attach a Basic {P} Energy card from your discard pile to 1 of your Benched {P} Pokémon.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02.5-076": {
  "cardId": "me02.5-076",
  "name": "Lillie's Clefairy ex",
  "category": "Pokemon",
  "hp": 190,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Full Moon Rondo",
    "cost": "Psychic,Colorless",
    "damage": "20+",
    "effect": "This attack does 20 more damage for each Benched Pokémon (both yours and your opponent's)."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Fairy Zone",
    "effect": "The Weakness of each of your opponent's {N} Pokémon in play is now {P}. (Apply Weakness as ×2.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Metal",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02.5-098": {
  "cardId": "me02.5-098",
  "name": "Spectrier",
  "category": "Pokemon",
  "hp": 120,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Spooky Shot",
    "cost": "Psychic",
    "damage": "30",
    "effect": null
   },
   {
    "name": "Phantasmal Barrage",
    "cost": "Psychic,Psychic,Colorless",
    "damage": null,
    "effect": "Discard all Energy from this Pokémon and place 12 damage counters on 1 of your opponent's Pokémon."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me02.5-184": {
  "cardId": "me02.5-184",
  "name": "Buddy-Buddy Poffin",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 2 Basic Pokémon with 70 HP or less and put them onto your Bench. Then, shuffle your deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02.5-213": {
  "cardId": "me02.5-213",
  "name": "Ultra Ball",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "You can use this card only if you discard 2 other cards from your hand.\nSearch your deck for a Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me03-062": {
  "cardId": "me03-062",
  "name": "Meowth ex",
  "category": "Pokemon",
  "hp": 170,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Tuck Tail",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "60",
    "effect": "Put this Pokémon and all attached cards into your hand."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Last-Ditch Catch",
    "effect": "Once during your turn, when you play this Pokémon from your hand onto your Bench, you may use this Ability. Search your deck for a Supporter card, reveal it, and put it into your hand. Then, shuffle your deck. You can't use more than 1 Ability that has \"Last-Ditch\" in its name each turn."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me03-081": {
  "cardId": "me03-081",
  "name": "Poké Pad",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for a Pokémon that doesn't have a Rule Box, reveal it, and put it into your hand. Then, shuffle your deck. (Pokémon ex, Pokémon V, etc. have Rule Boxes.)",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me03-088": {
  "cardId": "me03-088",
  "name": "Telepathic Psychic Energy",
  "category": "Energy",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": "Normal",
  "retreat": null,
  "types": [],
  "effect": "As long as this card is attached to a Pokémon, it provides {P} Energy.\nWhen you attach this card from your hand to a {P} Pokémon, search your deck for up to 2 Basic {P} Pokémon and put them onto your Bench. Then, shuffle your deck.",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me04-061": {
  "cardId": "me04-061",
  "name": "Metagross",
  "category": "Pokemon",
  "hp": 180,
  "stage": "Stage2",
  "suffix": null,
  "evolvesFrom": "Metang",
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Metal"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Bounce Back",
    "cost": "Metal",
    "damage": "60",
    "effect": "Switch out your opponent's Active Pokémon to the Bench. (Your opponent chooses the new Active Pokémon.)"
   },
   {
    "name": "Metallic Hammer",
    "cost": "Metal,Metal,Metal,Colorless",
    "damage": "150+",
    "effect": "You may discard 3 {M} Energy from this Pokémon and have this attack do 150 more damage."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Grass",
    "value": "-30"
   }
  ]
 },
 "me04-070": {
  "cardId": "me04-070",
  "name": "Patrat",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Bite",
    "cost": "Colorless",
    "damage": "10",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Watchful Eye",
    "effect": "Damage counters on each Pokémon (both yours and your opponent's) can't be moved to other Pokémon."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me04-080": {
  "cardId": "me04-080",
  "name": "Prism Tower",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Once during each player's turn, that player may discard 2 cards from their hand in order to draw a card.",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me04-082": {
  "cardId": "me04-082",
  "name": "Special Red Card",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "You can use this card only if your opponent has 3 or fewer Prize cards remaining.\n\nYour opponent shuffles their hand and puts it on the bottom of their deck. If they put any cards on the bottom of their deck in this way, they draw 3 cards.",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me05-005": {
  "cardId": "me05-005",
  "name": "Poltchageist",
  "category": "Pokemon",
  "hp": 30,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 0,
  "types": [
   "Grass"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Furtive Drop",
    "cost": "Colorless",
    "damage": null,
    "effect": "Place 1 damage counter on your opponent's Active Pokémon."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Hide 'n' Sneak",
    "effect": "Prevent all effects of your opponent's Pokémon's attacks and Abilities done to this Pokémon. (Damage is not an effect.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me05-006": {
  "cardId": "me05-006",
  "name": "Sinistcha",
  "category": "Pokemon",
  "hp": 60,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Poltchageist",
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Grass"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Matcha Spin",
    "cost": "Colorless",
    "damage": null,
    "effect": "If you have 6 or more Pokémon that have the Hide 'n' Sneak Ability in your discard pile, place 4 damage counters on each of your opponent's Pokémon."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Hide 'n' Sneak",
    "effect": "Prevent all effects of your opponent's Pokémon's attacks and Abilities done to this Pokémon. (Damage is not an effect.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me05-029": {
  "cardId": "me05-029",
  "name": "Slowpoke",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "All-You-Can-Yeet",
    "cost": "Psychic",
    "damage": null,
    "effect": "You may discard any number of cards from your hand."
   },
   {
    "name": "Headbutt",
    "cost": "Colorless,Colorless",
    "damage": "20",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me05-033": {
  "cardId": "me05-033",
  "name": "Shuppet",
  "category": "Pokemon",
  "hp": 50,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Hang Down",
    "cost": "Psychic",
    "damage": "10",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Hide 'n' Sneak",
    "effect": "Prevent all effects of your opponent's Pokémon's attacks and Abilities done to this Pokémon. (Damage is not an effect.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me05-034": {
  "cardId": "me05-034",
  "name": "Banette",
  "category": "Pokemon",
  "hp": 80,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Shuppet",
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Puppet Pull",
    "cost": "Psychic",
    "damage": "80",
    "effect": "You may search your deck for a card and put it into your hand. Then, shuffle your deck."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Hide 'n' Sneak",
    "effect": "Prevent all effects of your opponent's Pokémon's attacks and Abilities done to this Pokémon. (Damage is not an effect.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me05-039": {
  "cardId": "me05-039",
  "name": "Dhelmise",
  "category": "Pokemon",
  "hp": 140,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Vengeful Anchor",
    "cost": "Psychic",
    "damage": "30+",
    "effect": "If you have 4 or more Pokémon that have the Hide 'n' Sneak Ability in your discard pile, this attack does 140 more damage."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me05-078": {
  "cardId": "me05-078",
  "name": "Gwynn",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Discard up to 2 Pokémon that don't have a Rule Box from your hand, and draw 3 cards for each card you discarded in this way. (Pokémon ex, Pokémon V, etc. have Rule Boxes.)",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv05-024": {
  "cardId": "sv05-024",
  "name": "Rabsca",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Rellor",
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Grass"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Psychic",
    "cost": "Grass",
    "damage": "10+",
    "effect": "This attack does 30 more damage for each Energy attached to your opponent's Active Pokémon."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Spherical Shield",
    "effect": "Prevent all damage from and effects of attacks from your opponent's Pokémon done to your Benched Pokémon."
   }
  ],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv05-129": {
  "cardId": "sv05-129",
  "name": "Dudunsparce",
  "category": "Pokemon",
  "hp": 140,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Dunsparce",
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Land Crush",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "90",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Run Away Draw",
    "effect": "Once during your turn, you may draw 3 cards. If you drew any cards in this way, shuffle this Pokémon and all attached cards into your deck."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv06-141": {
  "cardId": "sv06-141",
  "name": "Bloodmoon Ursaluna ex",
  "category": "Pokemon",
  "hp": 260,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Blood Moon",
    "cost": "Colorless,Colorless,Colorless,Colorless,Colorless",
    "damage": "240",
    "effect": "During your next turn, this Pokémon can't attack."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Seasoned Skill",
    "effect": "Blood Moon used by this Pokémon costs {C} less for each Prize card your opponent has taken."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv06-158": {
  "cardId": "sv06-158",
  "name": "Lucky Helmet",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "If the Pokémon this card is attached to is in the Active Spot and is damaged by an attack from your opponent's Pokémon (even if this Pokémon is Knocked Out), draw 2 cards.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06-163": {
  "cardId": "sv06-163",
  "name": "Secret Box",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "You can use this card only if you discard 3 other cards from your hand.\n\nSearch your deck for an Item card, a Pokémon Tool card, a Supporter card, and a Stadium card, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06-166": {
  "cardId": "sv06-166",
  "name": "Boomerang Energy",
  "category": "Energy",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": "Special",
  "retreat": null,
  "types": [],
  "effect": "As long as this card is attached to a Pokémon, it provides {C} Energy.\n\nIf this card is discarded by an effect of an attack used by the Pokémon this card is attached to, attach this card from your discard pile to that Pokémon after attacking.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06.5-038": {
  "cardId": "sv06.5-038",
  "name": "Fezandipiti ex",
  "category": "Pokemon",
  "hp": 210,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Cruel Arrow",
    "cost": "Colorless,Colorless,Colorless",
    "damage": null,
    "effect": "This attack does 100 damage to 1 of your opponent's Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)"
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Flip the Script",
    "effect": "Once during your turn, if any of your Pokémon were Knocked Out during your opponent's last turn, you may draw 3 cards. You can't use more than 1 Flip the Script Ability each turn."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv06.5-047": {
  "cardId": "sv06.5-047",
  "name": "Kyurem",
  "category": "Pokemon",
  "hp": 130,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Dragon"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Trifrost",
    "cost": "Water,Water,Metal,Metal,Colorless",
    "damage": null,
    "effect": "Discard all Energy from this Pokémon. This attack does 110 damage to 3 of your opponent's Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)"
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Plasma Bane",
    "effect": "If your opponent has any cards in their discard pile that have \"Colress\" in the name, this Pokémon can use the Trifrost attack for {C}."
   }
  ],
  "weaknesses": [],
  "resistances": []
 },
 "sv06.5-054": {
  "cardId": "sv06.5-054",
  "name": "Academy at Night",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Once during each player's turn, that player may put a card from their hand on top of their deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06.5-061": {
  "cardId": "sv06.5-061",
  "name": "Night Stretcher",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Put a Pokémon or a Basic Energy card from your discard pile into your hand.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv07-058": {
  "cardId": "sv07-058",
  "name": "Slowking",
  "category": "Pokemon",
  "hp": 120,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Slowpoke",
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Seek Inspiration",
    "cost": "Psychic,Colorless",
    "damage": null,
    "effect": "Discard the top card of your deck, and if that card is a Pokémon that doesn't have a Rule Box, choose 1 of its attacks and use it as this attack. (Pokémon ex, Pokémon V, etc. have Rule Boxes.)"
   },
   {
    "name": "Super Psy Bolt",
    "cost": "Psychic,Psychic,Colorless",
    "damage": "120",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "sv08-013": {
  "cardId": "sv08-013",
  "name": "Rellor",
  "category": "Pokemon",
  "hp": 40,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Grass"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Collect",
    "cost": "Colorless",
    "damage": null,
    "effect": "Draw a card."
   },
   {
    "name": "Rollout",
    "cost": "Grass",
    "damage": "10",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv08-076": {
  "cardId": "sv08-076",
  "name": "Latias ex",
  "category": "Pokemon",
  "hp": 210,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Eon Blade",
    "cost": "Psychic,Psychic,Colorless",
    "damage": "200",
    "effect": "During your next turn, this Pokémon can't attack."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Skyliner",
    "effect": "Your Basic Pokémon in play have no Retreat Cost."
   }
  ],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "sv08-100": {
  "cardId": "sv08-100",
  "name": "Annihilape",
  "category": "Pokemon",
  "hp": 140,
  "stage": "Stage2",
  "suffix": null,
  "evolvesFrom": "Primeape",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fighting"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Tantrum",
    "cost": "Fighting",
    "damage": "130",
    "effect": "This Pokémon is now Confused."
   },
   {
    "name": "Destined Fight",
    "cost": "Fighting,Colorless",
    "damage": null,
    "effect": "Both Active Pokémon are Knocked Out."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Psychic",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv08.5-079": {
  "cardId": "sv08.5-079",
  "name": "Dunsparce",
  "category": "Pokemon",
  "hp": 60,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 0,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Gnaw",
    "cost": "Colorless",
    "damage": "10",
    "effect": null
   },
   {
    "name": "Dig",
    "cost": "Colorless,Colorless",
    "damage": "30",
    "effect": "Flip a coin. If heads, during your opponent's next turn, prevent all damage from and effects of attacks done to this Pokémon."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv08.5-080": {
  "cardId": "sv08.5-080",
  "name": "Dudunsparce",
  "category": "Pokemon",
  "hp": 140,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Dunsparce",
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Land Crush",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "90",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Run Away Draw",
    "effect": "Once during your turn, you may draw 3 cards. If you drew any cards in this way, shuffle this Pokémon and all attached cards into your deck."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv08.5-101": {
  "cardId": "sv08.5-101",
  "name": "Buddy-Buddy Poffin",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 2 Basic Pokémon with 70 HP or less and put them onto your Bench. Then, shuffle your deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv08.5-104": {
  "cardId": "sv08.5-104",
  "name": "Ciphermaniac's Codebreaking",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for 2 cards, shuffle your deck, then put those cards on top of it in any order.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv10-078": {
  "cardId": "sv10-078",
  "name": "Zeraora",
  "category": "Pokemon",
  "hp": 100,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Lightning"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Scratch",
    "cost": "Colorless",
    "damage": "20",
    "effect": null
   },
   {
    "name": "Thunder Raid",
    "cost": "Lightning,Lightning,Lightning",
    "damage": null,
    "effect": "Discard all Energy from this Pokémon, and this attack does 210 damage to 1 of your opponent's Benched Pokémon ex. (Don't apply Weakness and Resistance for Benched Pokémon.)"
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv10.5b-079": {
  "cardId": "sv10.5b-079",
  "name": "Air Balloon",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "The Retreat Cost of the Pokémon this card is attached to is {C}{C} less.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 }
};
