/**
 * Numeric parity test for the deformation-field port.
 *
 * The fixture is generated by `scripts/decke/gen-field-fixture.py`, which
 * EXECUTES the upstream `wiki/_raw/src/decke_field.py` rather than
 * re-implementing it — so this compares the TypeScript against Blender's actual
 * source, not against a second transcription of it.
 *
 * This is the gate that catches the failure mode the wiki warns about most
 * loudly: an axis or sign error that still animates plausibly. A wrong sign here
 * is invisible on screen until the character leans the wrong way.
 *
 *   node --import tsx --test src/character/decke/__tests__/field.test.ts
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'
import { Matrix4, Vector3 } from 'three'
import { field, fieldMatrix, FIELD_EPS } from '../field'
import { BODY_H, HINGE_REST } from '../constants'

type Case = {
  p: [number, number, number]
  angles: [number, number, number]
  field: [number, number, number]
  matrix: number[][] // row-major 4x4
}

type Fixture = {
  H: number
  EPS: number
  hinge_rest: [number, number, number]
  cases: Case[]
}

const here = dirname(fileURLToPath(import.meta.url))
const fixture: Fixture = JSON.parse(
  readFileSync(resolve(here, '../../../../scripts/decke/field-fixture.json'), 'utf8'),
)

// The Jacobian is a central difference with a 1e-4 step, so it carries real
// truncation error; positions are exact to double precision. Tolerances are set
// accordingly rather than with one loose number for both.
const POS_TOL = 1e-9
const ROT_TOL = 1e-6

test('fixture constants match the port', () => {
  assert.equal(fixture.H, BODY_H)
  assert.equal(fixture.EPS, FIELD_EPS)
  assert.deepEqual(fixture.hinge_rest, [HINGE_REST.x, HINGE_REST.y, HINGE_REST.z])
})

test('field() matches decke_field.field() on every case', () => {
  const out = new Vector3()
  let worst = 0
  let worstCase: Case | null = null

  for (const c of fixture.cases) {
    field(new Vector3(...c.p), c.angles[0], c.angles[1], c.angles[2], out)
    const d = Math.max(
      Math.abs(out.x - c.field[0]),
      Math.abs(out.y - c.field[1]),
      Math.abs(out.z - c.field[2]),
    )
    if (d > worst) {
      worst = d
      worstCase = c
    }
  }

  assert.ok(
    worst <= POS_TOL,
    `worst position error ${worst} > ${POS_TOL}\n` +
      `at p=${JSON.stringify(worstCase?.p)} angles=${JSON.stringify(worstCase?.angles)}`,
  )
})

test('fieldMatrix() matches decke_field.field_matrix() on every case', () => {
  const out = new Matrix4()
  let worst = 0
  let worstCase: Case | null = null

  for (const c of fixture.cases) {
    fieldMatrix(new Vector3(...c.p), c.angles[0], c.angles[1], c.angles[2], out)
    // three.js Matrix4.elements is COLUMN-major; the fixture is row-major.
    const e = out.elements
    for (let r = 0; r < 4; r++) {
      for (let col = 0; col < 4; col++) {
        const mine = e[col * 4 + r]
        const theirs = c.matrix[r][col]
        const d = Math.abs(mine - theirs)
        if (d > worst) {
          worst = d
          worstCase = c
        }
      }
    }
  }

  assert.ok(
    worst <= ROT_TOL,
    `worst matrix error ${worst} > ${ROT_TOL}\n` +
      `at p=${JSON.stringify(worstCase?.p)} angles=${JSON.stringify(worstCase?.angles)}`,
  )
})

test('the field is identity at zero, and the T->0 guard does not blow up', () => {
  const out = new Vector3()
  for (const p of [
    [0, 0, 0],
    [0.5, -0.3, 1.7],
    [-0.875, 0.575, 2.4],
  ] as const) {
    field(new Vector3(...p), 0, 0, 0, out)
    assert.ok(out.distanceTo(new Vector3(...p)) < 1e-12, `identity failed at ${p}`)

    // 1e-10 degrees is below the guard; the circular form would divide by ~0.
    field(new Vector3(...p), 1e-10, 1e-10, 0, out)
    assert.ok(Number.isFinite(out.x) && Number.isFinite(out.y) && Number.isFinite(out.z))
    assert.ok(out.distanceTo(new Vector3(...p)) < 1e-9, `guard failed at ${p}`)
  }
})

test('rider rotation is orthonormal and right-handed at every authored pose', () => {
  // The rider transform is DEFINED as the orthonormal part of the Jacobian. If
  // Gram-Schmidt has been ported wrong the basis silently stops being a rotation
  // and riders shear instead of following.
  const m = new Matrix4()
  for (const c of fixture.cases) {
    fieldMatrix(new Vector3(...c.p), c.angles[0], c.angles[1], c.angles[2], m)
    const e = m.elements
    const u0 = new Vector3(e[0], e[1], e[2])
    const u1 = new Vector3(e[4], e[5], e[6])
    const u2 = new Vector3(e[8], e[9], e[10])

    const label = `p=${JSON.stringify(c.p)} angles=${JSON.stringify(c.angles)}`
    assert.ok(Math.abs(u0.length() - 1) < 1e-9, `u0 not unit at ${label}`)
    assert.ok(Math.abs(u1.length() - 1) < 1e-9, `u1 not unit at ${label}`)
    assert.ok(Math.abs(u2.length() - 1) < 1e-9, `u2 not unit at ${label}`)
    assert.ok(Math.abs(u0.dot(u1)) < 1e-9, `u0.u1 not orthogonal at ${label}`)
    assert.ok(Math.abs(u0.dot(u2)) < 1e-9, `u0.u2 not orthogonal at ${label}`)
    assert.ok(Math.abs(u1.dot(u2)) < 1e-9, `u1.u2 not orthogonal at ${label}`)
    assert.ok(new Vector3().crossVectors(u0, u1).dot(u2) > 0, `left-handed at ${label}`)
  }
})

test('a bend moves the top of the body and pins the bottom', () => {
  // A sanity check with a known sign, because this is the exact class of error
  // that looks plausible on screen. +bend is FORWARD, i.e. toward -Y (his face).
  const bottom = new Vector3(0, 0, 0)
  const top = new Vector3(0, 0, BODY_H)
  const out = new Vector3()

  field(bottom, 18, 0, 0, out)
  assert.ok(out.distanceTo(bottom) < 1e-9, 'the base of the field must be a fixed point')

  field(top, 18, 0, 0, out)
  assert.ok(out.distanceTo(top) > 0.2, 'the top should travel appreciably at 18 deg')
  assert.ok(out.y > 0, '+bend must carry the top toward +Y in the raw field')
})
