/**
 * The playbook: 27 authored states as beats, and the evaluator that turns them
 * into a pose.
 *
 * The data is generated by `scripts/decke/gen-playbook.py` from the character
 * wiki's normative Python. Upstream's own generator has been broken since
 * 2026-08-16 (it reads Catmull-Rom profile tables that were deleted when the
 * flight timing became a runtime controller), so the committed
 * `_raw/playbook.json` is stale by four states and must not be used.
 *
 * WHY WE EVALUATE POSES OURSELVES INSTEAD OF USING AnimationMixer:
 *
 * The authored animation is not TRS keys on nodes. It is 47 NORMALISED CHANNELS
 * (`bend`, `mouth`, `lid_u`, `alert`, `m_curve`, ...) that each fan out to morph
 * influences, hinge angles, shader uniforms and node transforms through
 * non-linear mappings — `mouth` alone drives a hinge rotation, a whole-body tip
 * and a back-arch morph at once. Baking that into glTF clips would throw away
 * the channel semantics an LLM needs to drive ("40% of the way to a frown" is
 * not expressible against an AnimationClip), and would collide with
 * AdditiveAnimationBlendMode's documented inability to compose morph targets.
 *
 * Crossfading resolved poses instead of clips also means "blend from wherever he
 * actually is" is the natural implementation, which is what makes mid-emote
 * interruption look right.
 */
import { evalCurve, makeCurve, type Curve, type Key } from './curve'

export type Pose = Record<string, number>

export type Beat = {
  t_ms: number
  ease: 'ease' | 'lin' | 'step'
  pose: Record<string, number>
}

export type Modulation = {
  float_amp: number
  float_rate: number
  blink_rate: number
}

export type StateClip = {
  kind: 'clip'
  symbol: string | null
  duration_ms: number
  mod: string
  modulation: Modulation
  beats: Beat[]
  loop?: true
  /** The last beat is the FIRST BEAT COME ROUND AGAIN, so every curve gets one
   *  shared tangent at the seam instead of two terminal ones. Set by
   *  `windowClip`; see `sustain.ts`. */
  cyclic?: true
  orbit?: true
  overlay?: true
  spin?: true
  gaze_lock?: true
  vibrate_hz?: number
  linear_channels?: string[]
  flight_spans_ms?: [number, number][]
}

export type PlaybookDoc = {
  schema: string
  fps: number
  transition: {
    blend_ms: number
    policy: string
    idle_beat_ms: number
    snap_states: string[]
    /** state -> the channels that are already away from rest on its FIRST beat.
     *  `boot` is the interesting one: starting squashed and shut is its point. */
    non_resting_start: Record<string, string[]>
    /** state -> the channels still away from rest on its LAST beat. These have
     *  to be blended out explicitly; hub-and-spoke assumes a return to rest. */
    non_resting_end: Record<string, string[]>
  }
  rest_pose: Pose
  gaze_lock: string[]
  step_rates_hz: { sharp: number; slow: number }
  procedural: {
    idle_float: {
      base_hz: number
      ratios: [number, number, number]
      weights: [number, number, number]
      amplitude: Record<string, number>
      phase: Record<string, [number, number, number]>
    }
    prng: { a: number; m: number; seed: number }
    blink: {
      close_ms: number
      hold_ms: number
      open_ms: number
      interval_s: [number, number]
      double_p: number
      double_gap_ms: number
      first_offset_s: [number, number]
      lower_lid_ratio: number
    }
    gaze_flit: {
      interval_s: [number, number]
      amp_x: number
      amp_z: number
      move_ms: number
      first_offset_s: [number, number]
    }
    glance_away: {
      interval_s: [number, number]
      hold_ms: [number, number]
      amp_x: [number, number]
      amp_z: [number, number]
      first_offset_s: [number, number]
    }
  }
  flight: Record<string, unknown>
  symbol_atlas: {
    grid: [number, number]
    pixels: [number, number]
    cell_px: number
    sizes: Record<string, number>
    spinner_deg_per_s: number
    spin_deg_per_s: number
    scribble_hz: number
    spin_phase_deg: { L: number; R: number }
  }
  states: Record<string, StateClip>
  order: string[]
}

/** A state compiled to per-channel curves, ready to evaluate. */
export type CompiledState = {
  name: string
  clip: StateClip
  /** Only channels that actually move. Everything else stays at REST. */
  curves: Map<string, Curve>
  /** False if any eased curve had to fall back to the approximate interpolant. */
  exact: boolean
}

/**
 * Compile one state's sparse beats into dense per-channel curves.
 *
 * Beats are stored as DELTAS FROM REST — a channel missing from a beat is at its
 * rest value at that beat, not "unchanged since the last beat". Every beat is a
 * complete pose; the sparsity is only compression. Reading it as "unchanged"
 * would make channels stick at whatever they last held, which looks like a rig
 * that never returns to neutral.
 */
export function compileState(name: string, clip: StateClip, rest: Pose): CompiledState {
  // Which channels move at all in this state?
  const moving = new Set<string>()
  for (const b of clip.beats) for (const k of Object.keys(b.pose)) moving.add(k)

  const forcedLinear = new Set(clip.linear_channels ?? [])
  const curves = new Map<string, Curve>()
  let exact = true

  for (const ch of moving) {
    const keys: Key[] = clip.beats.map((b) => ({
      t: b.t_ms,
      v: ch in b.pose ? b.pose[ch] : (rest[ch] ?? 0),
      // A per-channel override wins over the beat's own tag. `sym_spin` must
      // stay LINEAR through the stepped vibrate beats or the dizzy spiral
      // freezes mid-rotation every time the body ticks.
      interp: forcedLinear.has(ch) ? 'lin' : b.ease,
    }))
    const c = makeCurve(keys, { cyclic: clip.cyclic })
    if (!c.exact) exact = false
    curves.set(ch, c)
  }

  return { name, clip, curves, exact }
}

export function compilePlaybook(doc: PlaybookDoc): Map<string, CompiledState> {
  const out = new Map<string, CompiledState>()
  for (const name of doc.order) {
    out.set(name, compileState(name, doc.states[name], doc.rest_pose))
  }
  return out
}

/** Evaluate a compiled state at `t` ms into a pose object (mutated in place). */
export function evalState(state: CompiledState, t: number, rest: Pose, out: Pose): Pose {
  // Start from rest so channels this state never touches read correctly. The
  // rest pose has NON-ZERO defaults (`orb_r = 0.5`, `single = 1`, `rl_z = 1`),
  // so zero-filling here would despawn his internal card and misplace the orbit.
  for (const k in rest) out[k] = rest[k]
  for (const [ch, curve] of state.curves) out[ch] = evalCurve(curve, t)
  return out
}

/** Linear blend between two poses. Used for state crossfades. */
export function blendPose(a: Pose, b: Pose, w: number, out: Pose): Pose {
  for (const k in a) out[k] = a[k] + (b[k] - a[k]) * w
  return out
}

export async function loadPlaybook(baseUrl: string): Promise<PlaybookDoc> {
  const res = await fetch(`${baseUrl}models/decke/playbook.json`)
  if (!res.ok) throw new Error(`playbook: ${res.status} ${res.statusText}`)
  return (await res.json()) as PlaybookDoc
}
