import { useEffect, useId, useState, type JSX } from 'react'
import { Icon } from '../../../components/Icon'
import { activitySummary, currentStep, isFailure, isRunning, sourceFavicons, stepLabel, type ActivityStep } from './activityState'
import { iconFor, kindOf, motionFor } from './toolKinds'
import { mergeSources, type Source } from './sourcesState'

export type { ActivityStep } from './activityState'
export function ActivityLine({ steps, busy, startedAt, waiting = false, sources = [], defaultOpen = false, onRetryStep }: { steps: ActivityStep[]; busy: boolean; startedAt?: number; waiting?: boolean; sources?: Source[]; defaultOpen?: boolean; onRetryStep?: (id: string) => void }): JSX.Element {
  const [open, setOpen] = useState(defaultOpen); const [now, setNow] = useState(Date.now()); const id = useId()
  useEffect(() => { if (!busy) return; const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer) }, [busy])
  const active = currentStep(steps); const elapsed = startedAt ? Math.max(0, Math.floor((now - startedAt) / 1000)) : 0
  const label = waiting ? 'Waiting for your OK' : active ? stepLabel(active) : 'Thinking…'; const kind = active ? kindOf(active.name) : 'other'; const researchSources = mergeSources([sources, ...steps.filter((step) => kindOf(step.name) === 'research').map((step) => step.sources)]); const favicons = sourceFavicons(researchSources)
  const summary = busy ? label : activitySummary(steps, elapsed); const failure = !busy && steps.some(isFailure)
  return <div className={['flex flex-col gap-[4px] text-[12px] leading-[18px]', failure ? 'text-warning' : 'text-text-muted'].join(' ')}><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpen(!open)} className="flex h-[28px] min-w-0 items-center gap-[7px] rounded-sm text-left hover:text-text-primary"><Icon name={iconFor(kind)} size={14} className={[busy && !waiting ? motionFor(kind) : '', 'shrink-0 text-action-primary'].join(' ')} /><span key={summary} role={busy ? 'status' : undefined} aria-live={busy ? 'polite' : undefined} aria-atomic="true" className="da-label min-w-0 truncate">{summary}</span>{busy && !waiting ? <span className="ml-auto shrink-0 font-mono tabular-nums text-text-muted">{elapsed}s</span> : null}{busy && favicons.urls.map((url) => <img key={url} src={url} alt="" className="h-[14px] w-[14px] shrink-0 rounded-[3px]" />)}{busy && favicons.more ? <span className="shrink-0 text-text-muted">+{favicons.more}</span> : null}<Icon name={open ? 'chevron-down' : 'chevron-right'} size={13} className="shrink-0" /></button><ul id={id} hidden={!open} className="flex flex-col gap-[3px] pl-[21px]">{steps.map((step) => { const failed = isFailure(step); const running = isRunning(step); return <li key={step.id} className={failed ? 'rounded-[7px] bg-warning/[0.07] px-[7px] py-[4px]' : ''}><div className="flex items-center gap-[6px]"><Icon name={iconFor(kindOf(step.name))} size={13} className={[running ? motionFor(kindOf(step.name)) : '', failed ? 'text-warning' : 'text-icon-muted'].join(' ')} /><span>{stepLabel(step)}</span>{failed && onRetryStep ? <button type="button" onClick={() => onRetryStep(step.id)} className="ml-auto text-action-primary hover:underline">Try again</button> : null}</div>{(step.summary || step.note) ? <p className="pl-[19px] text-text-muted">{step.summary || step.note}</p> : null}</li> })}</ul></div>
}
