// foil/provenance.ts — sidecar v3: honest mask provenance + the AI learning loop.
//
// Chey, 2026-08-07: "We'll want to mark when masks are generated by an AI as
// well, because once i've made a few hand-done masks, i want an AI to be able
// to learn from mine to be able to do its best at replicating it across other
// cards in similar sets/series - and then i want to be able to correct the
// agents' mask such that it can then observe the diff and continue to improve
// without me having to hand-paint all the masks."
//
// So provenance here is not a label — it is the record that makes that loop
// mechanical:
//
//   1. WHAT MADE ME        derivation_method + prior.source (+ prior.generator)
//   2. FROM WHAT           prior.generator.exemplars (the human masks it learned
//                          from) / correction.parent (the mask a human edited)
//   3. WHAT THE HUMAN      correction.{parentPng, parentDiffPng, metrics, grid}
//      CHANGED AFTERWARDS  — the training signal, kept as pixels AND numbers
//
// THE LABEL IS NEVER TRUSTED FROM THE CLIENT. `deriveMethod()` decides it by
// diffing the saved pixels against the pixels the claimed starting point
// actually produces. A caller can only *claim* a machine label by supplying a
// full generator identity (name/version/runId/exemplars) — see writeMaskRecord.
//
// See .claude/skills/mask-pipeline/SKILL.md § "Sidecar v3" for the schema.

import { createHash } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { readFile, writeFile, unlink, rm, readdir } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import {
  decodePng,
  diffMask,
  rasterizePriorAlpha,
  renderPriorPng,
  type DiffStats,
  type MaskPrior,
} from './mask-artifacts.js';
import type { RgbaImage } from './png.js';

export const SIDECAR_VERSION = 3;

/** alpha >= 128 counts as foil (same threshold as diffMask). */
const FOIL_THRESHOLD = 128;

// ── The taxonomy ───────────────────────────────────────────────────────────
//
// Five values, covering the four cases that must stay distinguishable:
// pure machine geometry / pure human / human-corrected-machine / machine-unreviewed.

export type DerivationMethod =
  /** Machine geometry only: a window/era rect baked to pixels, not a stroke painted on it. */
  | 'layout-flatten'
  /** Human-painted from scratch or straight from a layout/window prior. */
  | 'hand'
  /** Human-painted ON TOP of an existing NON-AI mask (a bake, or an earlier hand mask). */
  | 'hand-refined'
  /** Machine-generated by a mask generator, NOT yet looked at by a human. */
  | 'ai'
  /** An AI-derived mask a human then edited — the correction record is the product. */
  | 'ai-corrected';

export const DERIVATION_METHODS: readonly DerivationMethod[] = [
  'layout-flatten',
  'hand',
  'hand-refined',
  'ai',
  'ai-corrected',
];

/** Who actually put the pixels there. */
export type Authorship = 'human' | 'machine' | 'mixed';

/** Has a human looked at this mask? Drives the "unreviewed" badge + the queue. */
export type ReviewStatus =
  /** A human painted these pixels. */
  | 'human-authored'
  /** A human chose the geometry (window handles) but painted nothing. */
  | 'human-adjusted'
  /** Machine output no human has touched. NEVER an exemplar. */
  | 'unreviewed';

export const AUTHORSHIP_BY_METHOD: Record<DerivationMethod, Authorship> = {
  'layout-flatten': 'machine',
  hand: 'human',
  'hand-refined': 'human',
  ai: 'machine',
  'ai-corrected': 'mixed',
};

export const REVIEW_BY_METHOD: Record<DerivationMethod, ReviewStatus> = {
  'layout-flatten': 'human-adjusted',
  hand: 'human-authored',
  'hand-refined': 'human-authored',
  ai: 'unreviewed',
  'ai-corrected': 'human-authored',
};

/**
 * ANTI-FEEDBACK-COLLAPSE (the safeguard, enforced in code — not a convention).
 *
 * A generator that learns from its own unreviewed output converges on its own
 * mistakes. So exemplar eligibility is a property of WHO PAINTED THE PIXELS:
 *
 *   - `hand` / `hand-refined` — a human painted them. Ground truth, weight 1.
 *   - `ai-corrected`          — a human painted ON an AI mask. Real signal, but
 *                               anchored by what the AI proposed, so it is
 *                               deliberately worth LESS than an unanchored
 *                               human mask (weight 0.6).
 *   - `ai`                    — unreviewed machine output. Weight 0: it can
 *                               never be an exemplar, at any corpus size.
 *   - `layout-flatten`        — a rect the machine rasterized; teaches only the
 *                               rect the generator already knows. Weight 0.
 *
 * `selectExemplars()` is the ONLY sanctioned way to pick training masks; the
 * codify ritual and every generator go through it.
 */
export const EXEMPLAR_WEIGHT: Record<DerivationMethod, number> = {
  'layout-flatten': 0,
  hand: 1,
  'hand-refined': 1,
  ai: 0,
  'ai-corrected': 0.6,
};

export function isExemplarEligible(method: DerivationMethod): boolean {
  return EXEMPLAR_WEIGHT[method] > 0;
}

// ── Generator identity (the "what made me" half of the chain) ───────────────

/** One human mask a generator learned from. */
export interface ExemplarRef {
  cardId: string;
  variantId: number;
  /** The exemplar's own savedAt — pins WHICH version was learned from. */
  savedAt: string | null;
  /** The exemplar's method at selection time (always human-authored — see EXEMPLAR_WEIGHT). */
  method: DerivationMethod;
  /** Weight this exemplar carried in the run. */
  weight: number;
}

/**
 * Who/what generated a machine mask. Recorded verbatim on the mask AND carried
 * forward onto every human correction of it, so a correction can always answer
 * "which generator, which run, which exemplars produced the thing I fixed".
 */
export interface GeneratorIdentity {
  /** Stable generator name, e.g. 'window-artgate'. */
  name: string;
  /** Generator version — bump when its behavior changes meaning. */
  version: number;
  /** Model id when a model was involved; null for classical-CV generators. */
  modelId: string | null;
  /** Unique id for the batch this mask came out of (groups a trial batch). */
  runId: string;
  /** Everything needed to reproduce the run. */
  params: Record<string, number | string | boolean>;
  /** The human masks it learned from. Empty = it learned from nothing (say so). */
  exemplars: ExemplarRef[];
  /** Generator's own confidence in THIS mask, 0..1, or null if it emits none. */
  confidence: number | null;
  generatedAt: string;
}

// ── Correction record (the training signal) ────────────────────────────────

/** Where the human's corrections landed, as a coarse grid of change fractions. */
export interface CorrectionGrid {
  /** Grid is size × size cells, row-major from the TOP-LEFT of the mask. */
  size: number;
  /** Fraction of each cell's pixels the human changed, 0..1, 3 dp. */
  cells: number[];
}

export interface CorrectionRecord {
  /** The mask the human edited. Its pixels are kept at `parentPng`. */
  parent: {
    cardId: string;
    variantId: number;
    savedAt: string | null;
    method: DerivationMethod;
    /** sha256 of the parent PNG bytes — pins the exact pixels corrected. */
    sha256: string;
    /** Carried forward when the parent was machine-made. */
    generator: GeneratorIdentity | null;
  };
  /** Filename (in this mask's dir) of the parent mask's pixels. */
  parentPng: string;
  /** Filename of the human-vs-parent diff: GREEN added, RED removed. */
  parentDiffPng: string;
  /** Pixels the human ADDED to the parent. */
  addedPx: number;
  /** Pixels the human REMOVED from the parent. */
  removedPx: number;
  /** Foil pixels human and parent agree on. */
  unchangedPx: number;
  /** Jaccard(human, parent) — 1.0 = the parent was already right. */
  agreement: number;
  /** addedPx + removedPx. */
  changedPx: number;
  /** changedPx / (width*height) — how much of the face the human touched. */
  changedFraction: number;
  /** Bounding box of the changed pixels, UV y-up [x,y,w,h]; null when nothing changed. */
  bbox: [number, number, number, number] | null;
  /** Where the corrections concentrate. */
  grid: CorrectionGrid;
}

// ── Supersede record (a machine write that REPLACED a real mask) ───────────
//
// Distinct from `correction` on purpose. `correction` means "a human edited
// what was here" and is training signal. This means "a generator replaced what
// was here, and no human has agreed yet" — the opposite direction. Blurring
// them would feed a generator's own reshaping back as if a human had endorsed
// it, which is exactly what EXEMPLAR_WEIGHT exists to prevent.
//
// The replaced mask survives twice over: `.parent.png` holds its pixels for
// review, and `archiveDir` holds a VERBATIM copy of every artifact it had, so
// `restoreSuperseded()` puts the original back byte-for-byte — sha256-verified.
// A proposal you cannot un-propose is not a proposal.

export interface SupersededRecord {
  parent: {
    cardId: string;
    variantId: number;
    savedAt: string | null;
    method: DerivationMethod;
    sha256: string;
    generator: GeneratorIdentity | null;
  };
  /** Filename (in this mask's dir) of the replaced mask's pixels. */
  parentPng: string;
  /** Filename of the machine-vs-replaced diff: GREEN added, RED removed. */
  parentDiffPng: string;
  /** The generator run that did it — the handle `revert --run-id` uses. */
  runId: string;
  /** Directory (relative to the mask's own dir) of the verbatim archive. */
  archiveDir: string;
  /** basename → sha256 of the archived bytes. Restore verifies every one. */
  archive: Record<string, string>;
  addedPx: number;
  removedPx: number;
  unchangedPx: number;
  agreement: number;
  changedPx: number;
  changedFraction: number;
  bbox: [number, number, number, number] | null;
  grid: CorrectionGrid;
}

// ── The sidecar ────────────────────────────────────────────────────────────

/** Card context, so a generator lane can group by set/series with no DB. */
export interface MaskCardContext {
  setId: string | null;
  seriesSlug: string | null;
  name: string | null;
  number: string | null;
}

/** One compact ancestry entry (pixels are NOT kept beyond the direct parent). */
export interface LineageEntry {
  method: DerivationMethod;
  savedAt: string | null;
  source: MaskPrior['source'];
  generator: { name: string; version: number; runId: string } | null;
}

const MAX_LINEAGE = 8;

export interface MaskSidecarV3 {
  version: number;
  cardId: string;
  variantId: number;
  artworkKey: string;
  width: number;
  height: number;
  channel: string;
  /** THE honest label — derived server-side from pixels, never taken on trust. */
  derivation_method: DerivationMethod;
  /** Rollup of derivation_method (recomputed on read; a stale file cannot lie). */
  authorship: Authorship;
  reviewStatus: ReviewStatus;
  savedAt: string;
  /** URL of the scan the mask was drawn on — what a generator must consume. */
  artworkUrl: string | null;
  card?: MaskCardContext;
  prior: MaskPrior;
  priorPng?: string;
  diffPng?: string;
  /** RULE-vs-mask (v2 semantics, preserved): how wrong the era rule was. */
  diff?: DiffStats;
  /** HUMAN-vs-parent: what the human changed. Present only on a correction. */
  correction?: CorrectionRecord;
  /** MACHINE-vs-replaced: what a generator overwrote, and how to undo it. */
  supersedes?: SupersededRecord;
  /** Oldest → newest ancestry, this save last. Capped at MAX_LINEAGE. */
  lineage?: LineageEntry[];
}

// ── Migration: v1/v2 → v3, on read, without touching disk ──────────────────

function asMethod(raw: unknown): DerivationMethod | null {
  return typeof raw === 'string' && (DERIVATION_METHODS as readonly string[]).includes(raw)
    ? (raw as DerivationMethod)
    : null;
}

/**
 * Normalize ANY sidecar generation to the v3 shape in memory.
 *
 * v1 (no prior) and v2 both carried the hardcoded placeholder
 * `derivation_method: 'hand'`. That placeholder is only TRUE for masks that
 * predate this module — every one of them was drawn by Chey with a Pencil,
 * which is exactly what 'hand' means. So legacy files migrate to 'hand' and
 * that is honest, not a guess. From v3 on the label is computed from pixels.
 *
 * Derived fields (authorship/reviewStatus) are ALWAYS recomputed here, so a
 * hand-edited or stale sidecar can never claim a status its method denies.
 */
export function normalizeSidecar(raw: unknown): MaskSidecarV3 | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const s = raw as Record<string, unknown>;
  if (typeof s.cardId !== 'string' || typeof s.width !== 'number' || typeof s.height !== 'number') return null;

  const method = asMethod(s.derivation_method) ?? 'hand';
  const out: MaskSidecarV3 = {
    ...(s as unknown as MaskSidecarV3),
    version: typeof s.version === 'number' ? s.version : 1,
    derivation_method: method,
    authorship: AUTHORSHIP_BY_METHOD[method],
    reviewStatus: REVIEW_BY_METHOD[method],
    artworkKey: typeof s.artworkKey === 'string' ? s.artworkKey : s.cardId,
    artworkUrl: typeof s.artworkUrl === 'string' ? s.artworkUrl : null,
  };
  return out;
}

// ── Method derivation: the label the PIXELS support ────────────────────────

export interface StartingPoint {
  /** What the editor seeded the canvas with. */
  kind: 'layout' | 'window-bake' | 'mask';
  /** The parent mask, when kind === 'mask'. */
  parent?: { cardId: string; variantId: number; sidecar: MaskSidecarV3 | null; png: Buffer };
}

/**
 * Decide the honest method. `painted` is measured, not claimed: the saved
 * alpha is compared to the alpha the starting point actually rasterizes to.
 */
export function deriveMethod(startedFrom: StartingPoint['kind'], parentMethod: DerivationMethod | null, painted: boolean): DerivationMethod {
  if (!painted) {
    // Nothing changed since the seed. If the seed was a mask, this save is a
    // no-op re-save — keep the parent's honest label rather than inventing one.
    return parentMethod ?? 'layout-flatten';
  }
  if (parentMethod === 'ai' || parentMethod === 'ai-corrected') return 'ai-corrected';
  if (parentMethod !== null) return 'hand-refined';
  // Seeded from geometry (era rect or an adjusted window) and painted on:
  // that is a human mask, however it started.
  void startedFrom;
  return 'hand';
}

// ── Pixel helpers ──────────────────────────────────────────────────────────

export function alphaOf(img: RgbaImage): Uint8Array {
  const a = new Uint8Array(img.width * img.height);
  for (let i = 0; i < a.length; i++) a[i] = img.rgba[i * 4 + 3]!;
  return a;
}

export function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

/**
 * Human-vs-parent correction metrics + a spatial grid. Uses the same
 * foil threshold and diff PNG colors as the rule diff, so the two artifacts
 * are read the same way (GREEN = added, RED = removed).
 */
export function correctionMetrics(
  saved: RgbaImage,
  parentAlpha: Uint8Array,
  gridSize = 4,
): { png: Buffer; stats: DiffStats; changedPx: number; changedFraction: number; bbox: [number, number, number, number] | null; grid: CorrectionGrid } {
  const { width, height } = saved;
  const { png, stats } = diffMask(saved, parentAlpha);
  const cells = new Array<number>(gridSize * gridSize).fill(0);
  const cellCounts = new Array<number>(gridSize * gridSize).fill(0);
  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;
  let changedPx = 0;
  for (let y = 0; y < height; y++) {
    const gy = Math.min(gridSize - 1, Math.floor((y / height) * gridSize));
    for (let x = 0; x < width; x++) {
      const i = y * width + x;
      const gx = Math.min(gridSize - 1, Math.floor((x / width) * gridSize));
      const cell = gy * gridSize + gx;
      cellCounts[cell]!++;
      const inSaved = saved.rgba[i * 4 + 3]! >= FOIL_THRESHOLD;
      const inParent = parentAlpha[i]! >= FOIL_THRESHOLD;
      if (inSaved === inParent) continue;
      changedPx++;
      cells[cell]!++;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  const total = width * height;
  // UV y-up bbox — same space as prior.rect, so a generator can use it directly.
  const bbox: [number, number, number, number] | null =
    maxX < 0
      ? null
      : [
          Number((minX / width).toFixed(4)),
          Number((1 - (maxY + 1) / height).toFixed(4)),
          Number(((maxX - minX + 1) / width).toFixed(4)),
          Number(((maxY - minY + 1) / height).toFixed(4)),
        ];
  return {
    png,
    stats,
    changedPx,
    changedFraction: Number((changedPx / total).toFixed(6)),
    bbox,
    grid: {
      size: gridSize,
      cells: cells.map((c, i) => Number((c / (cellCounts[i] || 1)).toFixed(3))),
    },
  };
}

/**
 * Count pixels the human actually painted, relative to a starting alpha plane.
 *
 * `seamTolerant` matters when the start is a RASTERIZED RECT rather than a
 * stored mask. The editor bakes the window with canvas `roundRect` + `fill`;
 * this module rasterizes the same rect from a signed-distance field. Both are
 * correct, and both put ~0.5 coverage on the true edge — so they legitimately
 * disagree in the one-pixel antialiasing band. Measured on the WOTC window at
 * 490×674: 389 of 330,260 px cross the foil threshold differently, and ALL 389
 * sit in that band. Counting them would stamp every unpainted Flatten as
 * `hand`, which is exactly the lie sidecar v3 exists to stop.
 *
 * So a pixel counts as painted only where the SEED IS UNAMBIGUOUS — its 3×3
 * neighbourhood is entirely foil or entirely empty. A brush stroke (>= 4 px)
 * always clears that bar; a rasterizer seam never does. The residual blind
 * spot is a human painting a 1-px line exactly along the window edge, which is
 * both implausible and harmless (the next real stroke reclassifies the save).
 */
export function countPaintedOver(
  saved: RgbaImage,
  seed: Uint8Array,
  width: number,
  height: number,
  seamTolerant: boolean,
): number {
  let n = 0;
  for (let i = 0; i < seed.length; i++) {
    const inSaved = saved.rgba[i * 4 + 3]! >= FOIL_THRESHOLD;
    const inSeed = seed[i]! >= FOIL_THRESHOLD;
    if (inSaved === inSeed) continue;
    if (!seamTolerant) {
      n++;
      continue;
    }
    const x = i % width;
    const y = (i / width) | 0;
    let hi = 0;
    let lo = 0;
    for (let dy = -1; dy <= 1; dy++) {
      const ny = y + dy;
      if (ny < 0 || ny >= height) continue;
      for (let dx = -1; dx <= 1; dx++) {
        const nx = x + dx;
        if (nx < 0 || nx >= width) continue;
        if (seed[ny * width + nx]! >= FOIL_THRESHOLD) hi++;
        else lo++;
      }
    }
    if (hi === 0 || lo === 0) n++; // seed unambiguous here ⇒ a real edit
  }
  return n;
}

// ── Paths ──────────────────────────────────────────────────────────────────

export interface MaskPaths {
  dir: string;
  png: string;
  json: string;
  prior: string;
  diff: string;
  parent: string;
  parentDiff: string;
}

export function maskPathsIn(masksDir: string, cardId: string, variantId: string | number): MaskPaths {
  const dir = join(masksDir, cardId);
  return {
    dir,
    png: join(dir, `${variantId}.png`),
    json: join(dir, `${variantId}.json`),
    prior: join(dir, `${variantId}.prior.png`),
    diff: join(dir, `${variantId}.diff.png`),
    parent: join(dir, `${variantId}.parent.png`),
    parentDiff: join(dir, `${variantId}.parent.diff.png`),
  };
}

export function readSidecarFile(masksDir: string, cardId: string, variantId: string | number): Promise<MaskSidecarV3 | null> {
  return readFile(maskPathsIn(masksDir, cardId, variantId).json, 'utf8')
    .then((t) => normalizeSidecar(JSON.parse(t) as unknown))
    .catch(() => null);
}

/** Where a generator run parks the mask it replaced. Committed with the corpus. */
export function archiveDirName(variantId: string | number, runId: string): string {
  return join('superseded', `${variantId}.${runId.replace(/[^A-Za-z0-9._-]/g, '_')}`);
}

/**
 * The archive is SELF-DESCRIBING on disk (`archive.json`), not merely pointed
 * at by the sidecar. That matters: once Chey corrects a generated mask the live
 * sidecar stops being about the supersede, but his original must still be one
 * command away. So the undo reads the manifest from the archive itself.
 */
export interface ArchiveManifest {
  version: 1;
  cardId: string;
  variantId: number;
  runId: string;
  archivedAt: string;
  /** The replaced mask's method — what a restore puts back. */
  method: DerivationMethod;
  /** basename → sha256 of the archived bytes. */
  files: Record<string, string>;
}

const ARCHIVE_MANIFEST = 'archive.json';

/**
 * Copy every artifact currently on disk into the run's archive, VERBATIM, and
 * drop a manifest beside them. Returns basename → sha256 so a restore can
 * prove it put back the same BYTES, not a re-serialization that merely looks
 * equivalent.
 */
async function archiveExisting(
  paths: MaskPaths,
  cardId: string,
  variantId: string,
  runId: string,
  method: DerivationMethod,
): Promise<Record<string, string>> {
  const dir = join(paths.dir, archiveDirName(variantId, runId));
  mkdirSync(dir, { recursive: true });
  const files: Record<string, string> = {};
  for (const src of [paths.png, paths.json, paths.prior, paths.diff, paths.parent, paths.parentDiff]) {
    const buf = await readFile(src).catch(() => null);
    if (!buf) continue;
    const name = basename(src);
    await writeFile(join(dir, name), buf);
    files[name] = sha256(buf);
  }
  const manifest: ArchiveManifest = {
    version: 1,
    cardId,
    variantId: Number(variantId),
    runId,
    archivedAt: new Date().toISOString(),
    method,
    files,
  };
  await writeFile(join(dir, ARCHIVE_MANIFEST), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return files;
}

export interface FoundArchive {
  cardId: string;
  variantId: number;
  runId: string;
  /** Absolute path of the archive directory. */
  dir: string;
  manifest: ArchiveManifest;
}

/** Every generator archive on disk, optionally filtered to one run. */
export async function findArchives(masksDir: string, runId?: string | null): Promise<FoundArchive[]> {
  const out: FoundArchive[] = [];
  const cardDirs = await readdir(masksDir).catch(() => [] as string[]);
  for (const cardId of cardDirs) {
    if (cardId === 'codified') continue;
    const supDir = join(masksDir, cardId, 'superseded');
    const runs = await readdir(supDir).catch(() => [] as string[]);
    for (const r of runs) {
      const dir = join(supDir, r);
      const raw = await readFile(join(dir, ARCHIVE_MANIFEST), 'utf8').catch(() => null);
      if (!raw) continue;
      const manifest = JSON.parse(raw) as ArchiveManifest;
      if (runId && manifest.runId !== runId) continue;
      out.push({ cardId, variantId: manifest.variantId, runId: manifest.runId, dir, manifest });
    }
  }
  return out.sort((a, b) => (a.cardId === b.cardId ? a.variantId - b.variantId : a.cardId < b.cardId ? -1 : 1));
}

export interface RestoreResult {
  cardId: string;
  variantId: number;
  runId: string;
  /** Files put back, with the sha256 that was verified on each. */
  restored: { file: string; sha256: string }[];
  /** The method the restored mask carries — i.e. what Chey gets back. */
  method: DerivationMethod;
}

/**
 * Put back exactly what a generator run replaced. Byte-for-byte: every file is
 * read from the archive and re-hashed against the manifest recorded at
 * supersede time, and the WHOLE archive is verified before a single live file
 * is deleted — so a corrupt archive can never turn "undo" into "lose both".
 */
export async function restoreArchive(masksDir: string, found: FoundArchive): Promise<RestoreResult> {
  const paths = maskPathsIn(masksDir, found.cardId, found.variantId);
  const staged: { name: string; buf: Buffer; sha: string }[] = [];
  for (const [name, sha] of Object.entries(found.manifest.files)) {
    const buf = await readFile(join(found.dir, name));
    const got = sha256(buf);
    if (got !== sha) throw new Error(`archive ${found.dir}/${name} is corrupt (sha256 ${got} != ${sha})`);
    staged.push({ name, buf, sha });
  }
  if (!staged.some((s) => s.name === `${found.variantId}.png`)) {
    throw new Error(`archive ${found.dir} has no ${found.variantId}.png — refusing to delete the live mask`);
  }

  for (const f of [paths.png, paths.json, paths.prior, paths.diff, paths.parent, paths.parentDiff]) {
    await unlink(f).catch(() => undefined);
  }
  for (const s of staged) await writeFile(join(paths.dir, s.name), s.buf);
  await rm(found.dir, { recursive: true, force: true });
  const left = await readdir(join(paths.dir, 'superseded')).catch(() => null);
  if (left && left.length === 0) await rm(join(paths.dir, 'superseded'), { recursive: true, force: true });

  const back = await readSidecarFile(masksDir, found.cardId, found.variantId);
  return {
    cardId: found.cardId,
    variantId: found.variantId,
    runId: found.runId,
    restored: staged.map((s) => ({ file: s.name, sha256: s.sha })),
    method: back?.derivation_method ?? found.manifest.method,
  };
}

// ── THE single write path ──────────────────────────────────────────────────

export interface WriteMaskInput {
  masksDir: string;
  cardId: string;
  variantId: string;
  /** The mask PNG bytes (alpha = coverage). */
  png: Buffer;
  width: number;
  height: number;
  /** The deterministic era-rule prior (always recorded — keeps the codify score alive). */
  prior: MaskPrior;
  /** What the canvas was seeded with. Only affects which pixels `painted` is measured against. */
  startedFrom: StartingPoint['kind'];
  /** Claimed parent (cardId/variantId) when startedFrom === 'mask'. */
  parentRef?: { cardId: string; variantId: number } | null;
  artworkUrl?: string | null;
  card?: MaskCardContext;
  /**
   * ONLY a real generator may claim a machine label, and only by handing over
   * a full identity. No identity ⇒ the method is derived from pixels.
   */
  machine?: GeneratorIdentity | null;
  /**
   * Machine writes only: explicit consent to land on top of a mask that is
   * already there — including a HUMAN one. Without it, a generator write over
   * anything but its own unreviewed output THROWS. With it, every artifact the
   * mask had is archived verbatim under `superseded/<variantId>.<runId>/`,
   * `.parent.png` keeps the replaced pixels, and `supersedes` records the
   * sha256s that make `restoreSuperseded()` an exact undo.
   */
  supersede?: { runId: string } | null;
}

/**
 * Write a mask + every provenance artifact, stamping the method the pixels
 * support. Used by the foil-lab PUT route AND by generators — one path, so
 * "every write path stamps honestly" is structural, not a promise.
 */
export async function writeMaskRecord(input: WriteMaskInput): Promise<MaskSidecarV3> {
  const { masksDir, cardId, variantId, png, width, height, prior } = input;
  const paths = maskPathsIn(masksDir, cardId, variantId);
  const saved = decodePng(png);
  if (saved.width !== width || saved.height !== height) throw new Error('png dimensions do not match width/height');

  // ── The parent: what this save is replacing / was painted on top of ──
  //
  // SAFETY RULE: whatever the client claims, if the file at the target path is
  // unreviewed machine output ('ai'), it IS the parent. Otherwise a client that
  // forgot to report the parent would silently launder an AI mask into 'hand'
  // and the correction signal — the whole point — would be lost.
  const existing = await readSidecarFile(masksDir, cardId, variantId);
  let parentRef = input.parentRef ?? null;
  if (existing?.derivation_method === 'ai') parentRef = { cardId, variantId: Number(variantId) };

  // A generator landing on an existing mask must say so out loud. Silence used
  // to mean "overwrite", which is how human work disappears.
  const supersede = input.machine ? (input.supersede ?? null) : null;
  if (input.machine && existing && !supersede) {
    throw new Error(
      `${cardId}/${variantId} already has a ${existing.derivation_method} mask. A generator may only replace it with ` +
        'an explicit supersede { runId } — which archives the original byte-for-byte so `revert --run-id` undoes it.',
    );
  }

  let parentSidecar: MaskSidecarV3 | null = null;
  let parentPngBuf: Buffer | null = null;
  if (parentRef) {
    const pp = maskPathsIn(masksDir, parentRef.cardId, parentRef.variantId);
    parentPngBuf = await readFile(pp.png).catch(() => null);
    if (parentPngBuf) parentSidecar = await readSidecarFile(masksDir, parentRef.cardId, parentRef.variantId);
    else parentRef = null; // claimed a parent that isn't on disk — treat as none
  }

  // ── `painted`: measured against the pixels the starting point produces ──
  let startingAlpha: Uint8Array;
  let seamTolerant: boolean;
  if (parentPngBuf) {
    // Both masks came out of the SAME rasterizer (the editor canvas), so an
    // exact comparison is correct — every differing pixel is a human stroke.
    startingAlpha = alphaOf(decodePng(parentPngBuf));
    seamTolerant = false;
  } else {
    // Geometry seed. A window bake starts from the ADJUSTED rect when there is
    // one (that is what MaskEditor/Flatten rasterize); otherwise the era rule.
    const geom: MaskPrior =
      input.startedFrom === 'window-bake' && prior.window
        ? { ...prior, rect: prior.window.rect, radius: prior.window.radius }
        : prior;
    startingAlpha = rasterizePriorAlpha(width, height, geom);
    seamTolerant = true;
  }
  const painted = countPaintedOver(saved, startingAlpha, width, height, seamTolerant) > 0;

  const machine = input.machine ?? null;
  const method: DerivationMethod = machine
    ? 'ai'
    : deriveMethod(input.startedFrom, parentSidecar?.derivation_method ?? (parentPngBuf ? 'hand' : null), painted);

  // ── prior.source + generator carry-forward ──
  const inheritedGenerator =
    machine ??
    parentSidecar?.prior?.generator ??
    (parentSidecar?.correction?.parent.generator ?? null);
  const source: MaskPrior['source'] = machine
    ? 'ai'
    : parentSidecar && (parentSidecar.derivation_method === 'ai' || parentSidecar.derivation_method === 'ai-corrected')
      ? 'ai'
      : parentRef
        ? 'mask'
        : input.startedFrom === 'window-bake' && prior.window
          ? 'window'
          : 'layout';

  const replacedRef =
    parentRef && parentSidecar
      ? { cardId: parentRef.cardId, variantId: parentRef.variantId, sidecar: parentSidecar }
      : supersede && existing
        ? { cardId, variantId: Number(variantId), sidecar: existing }
        : null;

  const fullPrior: MaskPrior = {
    ...prior,
    source,
    ...(inheritedGenerator ? { generator: inheritedGenerator } : {}),
    ...(replacedRef
      ? {
          parentMask: {
            cardId: replacedRef.cardId,
            variantId: replacedRef.variantId,
            savedAt: replacedRef.sidecar.savedAt ?? null,
            method: replacedRef.sidecar.derivation_method,
          },
        }
      : {}),
  };

  // ── Rule-vs-mask artifacts (v2 semantics — the codify score) ──
  const ruleAlpha = rasterizePriorAlpha(width, height, prior);
  const priorPng = renderPriorPng(width, height, prior);
  const { png: diffPng, stats } = diffMask(saved, ruleAlpha);

  // ── Human-vs-parent artifacts (the correction signal) ──
  let correction: CorrectionRecord | undefined;
  if (parentRef && parentPngBuf && painted && !machine) {
    const m = correctionMetrics(saved, alphaOf(decodePng(parentPngBuf)));
    correction = {
      parent: {
        cardId: parentRef.cardId,
        variantId: parentRef.variantId,
        savedAt: parentSidecar?.savedAt ?? null,
        method: parentSidecar?.derivation_method ?? 'hand',
        sha256: sha256(parentPngBuf),
        generator: parentSidecar?.prior?.generator ?? null,
      },
      parentPng: `${variantId}.parent.png`,
      parentDiffPng: `${variantId}.parent.diff.png`,
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    mkdirSync(paths.dir, { recursive: true });
    await writeFile(paths.parent, parentPngBuf);
    await writeFile(paths.parentDiff, m.png);
  }

  // ── Machine-vs-replaced artifacts + the verbatim undo archive ──
  //
  // Order matters: archive FIRST (while the originals are still on disk),
  // then write the parent pixels + change map, then the sidecar. A crash
  // between steps leaves the archive intact, which is the safe direction.
  let supersedes: SupersededRecord | undefined;
  if (supersede && existing) {
    const replacedPng = await readFile(paths.png).catch(() => null);
    if (!replacedPng) {
      throw new Error(`${cardId}/${variantId} has a sidecar but no mask PNG — refusing to supersede a half-record`);
    }
    const archive = await archiveExisting(paths, cardId, variantId, supersede.runId, existing.derivation_method);
    const m = correctionMetrics(saved, alphaOf(decodePng(replacedPng)));
    supersedes = {
      parent: {
        cardId,
        variantId: Number(variantId),
        savedAt: existing.savedAt ?? null,
        method: existing.derivation_method,
        sha256: sha256(replacedPng),
        generator: existing.prior?.generator ?? null,
      },
      parentPng: `${variantId}.parent.png`,
      parentDiffPng: `${variantId}.parent.diff.png`,
      runId: supersede.runId,
      archiveDir: archiveDirName(variantId, supersede.runId),
      archive,
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    mkdirSync(paths.dir, { recursive: true });
    await writeFile(paths.parent, replacedPng);
    await writeFile(paths.parentDiff, m.png);
  }

  // ── Lineage: the parent's chain (which already ENDS with the parent's own
  // entry — don't append it twice) plus this save. Pre-v3 parents have no
  // lineage array, so synthesize their single entry from what they do record.
  const savedAt = new Date().toISOString();
  const ancestor = parentSidecar ?? (supersede ? existing : null);
  const parentLineage: LineageEntry[] = ancestor
    ? (ancestor.lineage ?? [
        {
          method: ancestor.derivation_method,
          savedAt: ancestor.savedAt ?? null,
          source: ancestor.prior?.source ?? 'layout',
          generator: ancestor.prior?.generator
            ? {
                name: ancestor.prior.generator.name,
                version: ancestor.prior.generator.version,
                runId: ancestor.prior.generator.runId,
              }
            : null,
        },
      ])
    : [];
  const lineage: LineageEntry[] = [
    ...parentLineage,
    {
      method,
      savedAt,
      source,
      generator: machine ? { name: machine.name, version: machine.version, runId: machine.runId } : null,
    },
  ].slice(-MAX_LINEAGE);

  const sidecar: MaskSidecarV3 = {
    version: SIDECAR_VERSION,
    cardId,
    variantId: Number(variantId),
    // Identity rule (unchanged since v2): a mask belongs to the card's SCAN.
    artworkKey: cardId,
    width,
    height,
    channel: 'alpha',
    derivation_method: method,
    authorship: AUTHORSHIP_BY_METHOD[method],
    reviewStatus: REVIEW_BY_METHOD[method],
    savedAt,
    artworkUrl: input.artworkUrl ?? existing?.artworkUrl ?? null,
    ...(input.card ? { card: input.card } : existing?.card ? { card: existing.card } : {}),
    prior: fullPrior,
    priorPng: `${variantId}.prior.png`,
    diffPng: `${variantId}.diff.png`,
    diff: stats,
    ...(correction ? { correction } : {}),
    ...(supersedes ? { supersedes } : {}),
    lineage,
  };

  mkdirSync(paths.dir, { recursive: true });
  await writeFile(paths.png, png);
  await writeFile(paths.prior, priorPng);
  await writeFile(paths.diff, diffPng);
  // A save with neither a correction nor a supersede must not leave a STALE
  // parent artifact behind.
  if (!correction && !supersedes) {
    await unlink(paths.parent).catch(() => undefined);
    await unlink(paths.parentDiff).catch(() => undefined);
  }
  await writeFile(paths.json, JSON.stringify(sidecar, null, 2) + '\n', 'utf8');
  return sidecar;
}
