import { useEffect, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { api } from '../../lib/api'
import { useAccess } from '../../lib/access'
import type { AiCost, AiUsageDetail } from '../../lib/adminTypes'
import { Button, DataTable, DataTableToolbar, EmptyState } from '../../components/ui'
import { Sheet } from '../../components/ui/Sheet'
import { selectClass, fmtDate } from './shared'
export const costLabel = (cost: AiCost) => cost.usd === null || cost.source === 'unknown' ? 'Unknown cost' : `$${cost.usd} USD${cost.coverage === 'partial' ? ' (partial)' : ''}${cost.source === 'token_rate_estimate' ? ' (estimate)' : ''}`
const categories: Record<string, string> = { response: 'Standard response', research: 'Research', planning: 'In-depth planning' }
function ContentProjection({ data }: { data: AiUsageDetail }) {
  return <section className="space-y-[12px]"><h3 className="font-semibold text-text-primary">Conversation content</h3>{data.contentStatus === 'shared' && data.content ? <><p className="text-[13px] text-text-muted">Shared under the current conversation consent.</p><h4 className="font-semibold text-text-primary">User message</h4><p className="whitespace-pre-wrap break-words text-text-body">{data.content.asked}</p><h4 className="font-semibold text-text-primary">Deck-E reply</h4><p className="whitespace-pre-wrap break-words text-text-body">{data.content.answered}</p></> : <p className="text-text-muted">{data.contentStatus === 'revoked' ? 'Sharing withdrawn. Conversation content is hidden.' : data.contentStatus === 'not_shared' ? 'Not shared. Only usage metadata is available.' : 'Conversation content unavailable. Usage metadata is retained.'}</p>}</section>
}
function RequestContent({ data }: { data: AiUsageDetail }) {
  return <div className="space-y-[20px]"><dl className="grid gap-[12px] text-[14px] sm:grid-cols-2">{[['User', data.request.userId], ['Started', fmtDate(data.request.startedAt)], ['Status', data.request.status], ['Category', categories[data.request.category]], ['Observed cost', costLabel(data.request.cost)], ['Charge mode', data.request.chargeMode], ['Build SHA', data.request.buildSha ?? 'Not recorded'], ['Pull request', data.request.buildPr === null ? 'Not recorded' : String(data.request.buildPr)]].map(([label, value]) => <div key={label}><dt className="text-text-muted">{label}</dt><dd className="break-all text-text-primary">{value}</dd></div>)}</dl><ContentProjection data={data} /><DataTable label="Provider operations" rows={data.operations} getRowId={o => o.id} empty="No provider operation recorded." columns={[
    { id: 'date', header: 'Started', cell: o => fmtDate(o.startedAt) }, { id: 'category', header: 'Category', cell: o => categories[o.category] ?? o.category }, { id: 'model', header: 'Model', cell: o => o.modelId ?? 'Not recorded' }, { id: 'status', header: 'Status', cell: o => o.status }, { id: 'cost', header: 'Observed cost', cell: o => costLabel(o.cost) }, { id: 'tokens', header: 'Input / output tokens', cell: o => `${o.tokens.inputTokens ?? 'Unknown'} / ${o.tokens.outputTokens ?? 'Unknown'}` },
  ]} /></div>
}
function UsageDetail({ selected, close }: { selected: { id: string; conversation: boolean }; close: () => void }) {
  const access = useAccess(), [offset, setOffset] = useState(0), [turn, setTurn] = useState<string | null>(null), [visible, setVisible] = useState(document.visibilityState === 'visible')
  const contentRef = useRef<HTMLDivElement>(null), turnRef = useRef<HTMLElement>(null)
  const query = useQuery({ queryKey: ['admin', access.identity, access.revision, 'ai-usage-detail', selected, offset], queryFn: async ({ signal }) => selected.conversation ? api.adminAiConversation(selected.id, new URLSearchParams({ offset: String(offset), limit: '25' }).toString(), signal) : { items: [await api.adminAiRequest(selected.id, signal)], total: 1, limit: 25, offset: 0 }, enabled: visible && access.actorCapabilities.canReadSharedConversations, staleTime: 0, gcTime: 0, retry: false, refetchInterval: 10000, refetchOnWindowFocus: 'always' })
  useEffect(() => { const update = () => setVisible(document.visibilityState === 'visible'); document.addEventListener('visibilitychange', update); return () => document.removeEventListener('visibilitychange', update) }, [])
  const fresh = visible && !query.isFetching && !query.error ? query.data : undefined
  const activeTurn = selected.conversation ? fresh?.items.find(d => d.request.id === turn) : fresh?.items[0]
  useEffect(() => {
    const body = contentRef.current, detail = turnRef.current
    if (turn && body && detail) {
      // Move only the sheet body. scrollIntoView also scrolls overflow-hidden
      // ancestors, displacing the pinned header and its Close control.
      body.scrollTop += detail.getBoundingClientRect().top - body.getBoundingClientRect().top - 16
    }
  }, [turn])
  return <Sheet title={selected.conversation ? 'Conversation usage' : 'Request usage'} size="lg" onClose={close} contentRef={contentRef}><div className="space-y-[20px]"><p className="text-[13px] text-text-muted">Content is returned only when current sharing consent permits it. Unknown costs are not treated as zero. Failed or incomplete requests may have partial spend.</p><DataTable label="Conversation turns" rows={fresh?.items ?? []} getRowId={d => d.request.id} loading={query.isPending} refreshing={query.isFetching && !query.isPending} error={query.error?.message} onRetry={() => void query.refetch()} pagination={selected.conversation ? { offset, pageSize: 25, total: query.data?.total ?? 0, onOffsetChange: value => { setOffset(value); setTurn(null) } } : undefined} columns={[{ id: 'turn', header: 'Turn', cell: d => d.request.seq === null ? 'Not recorded' : d.request.seq + 1 }, { id: 'started', header: 'Started', cell: d => fmtDate(d.request.startedAt) }, { id: 'category', header: 'Category', cell: d => categories[d.request.category] }, { id: 'cost', header: 'Observed cost', cell: d => costLabel(d.request.cost) }, ...(selected.conversation ? [{ id: 'details', header: 'Details', cell: (d: AiUsageDetail) => <Button variant="ghost" size="sm" aria-label={`View turn ${d.request.seq === null ? d.request.id : d.request.seq + 1}`} aria-pressed={turn === d.request.id} aria-controls="selected-usage-turn" onClick={() => setTurn(d.request.id)}>View turn</Button> }] : [])]} />{activeTurn && <section ref={turnRef} id="selected-usage-turn" aria-label="Selected conversation turn" className="min-w-0 space-y-[16px]">{selected.conversation && <Button variant="ghost" size="sm" onClick={() => { setTurn(null); if (contentRef.current) contentRef.current.scrollTop = 0 }}>Back to turns</Button>}<RequestContent data={activeTurn} /></section>}</div></Sheet>
}
function UsageTable() {
  const access = useAccess(), [offset, setOffset] = useState(0), [pageSize, setPageSize] = useState(25), [selected, setSelected] = useState<{ id: string; conversation: boolean } | null>(null)
  const initial = { userId: '', conversationId: '', category: '', status: '', from: '', to: '', modelId: '', buildSha: '', buildPr: '', costSource: '' }
  const [draft, setDraft] = useState(initial), [filters, setFilters] = useState(initial)
  const params = new URLSearchParams({ ...Object.fromEntries(Object.entries(filters).filter(([,v]) => v !== '')), limit: String(pageSize), offset: String(offset) }).toString()
  const query = useQuery({ queryKey: ['admin', access.identity, access.revision, 'ai-usage', params], queryFn: ({ signal }) => api.adminAiUsage(params, signal), enabled: access.ready && access.actorCapabilities.canReadSharedConversations, retry: false, staleTime: 0, gcTime: 0, refetchOnWindowFocus: true })
  return <section className="min-w-0 space-y-[20px]"><h2 className="font-display text-[24px] text-text-primary">AI usage</h2><p className="max-w-[760px] text-text-muted">Server-recorded requests, provider operations and observed costs, newest first. Conversation content requires current sharing consent. These observations do not change historical credit charges.</p>{query.data && !query.isFetching && <p role="status" className="text-[14px] text-text-muted">Known spend: ${query.data.aggregate.knownUsd} USD across {query.data.aggregate.knownCount} priced provider operations; {query.data.aggregate.unknownCount} provider operations have unknown cost. This is a partial sum when costs are missing.</p>}<DataTable label="AI usage requests" rows={query.data?.items ?? []} getRowId={row => row.id} loading={query.isPending} refreshing={query.isFetching && !query.isPending} error={query.error?.message} onRetry={() => void query.refetch()} pagination={{ offset, pageSize, total: query.data?.total ?? 0, onOffsetChange: setOffset, onPageSizeChange: setPageSize }} toolbar={<DataTableToolbar label="Filter AI usage" onSubmit={() => { setFilters(draft); setOffset(0) }} onReset={() => { setDraft(initial); setFilters(initial); setOffset(0) }}>
    {(['userId', 'conversationId', 'modelId', 'buildSha', 'buildPr', 'from', 'to'] as const).map(key => <label key={key} className="text-[14px] font-semibold text-text-secondary">{{ userId: 'User ID', conversationId: 'Conversation ID', modelId: 'Model', buildSha: 'Build SHA', buildPr: 'PR number', from: 'From date', to: 'To date' }[key]}<input aria-label={{ userId: 'Usage user ID', conversationId: 'Usage conversation ID', modelId: 'Usage model', buildSha: 'Usage build SHA', buildPr: 'Usage PR', from: 'Usage from', to: 'Usage to' }[key]} type={key === 'from' || key === 'to' ? 'date' : 'text'} className={selectClass + ' mt-[6px] max-w-[260px]'} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}
    <label className="text-[14px] font-semibold text-text-secondary">Category<select aria-label="Usage category" className={selectClass} value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}><option value="">All categories</option>{Object.entries(categories).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-[14px] font-semibold text-text-secondary">Status<select aria-label="Usage status" className={selectClass} value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value })}><option value="">All statuses</option>{['started','completed','failed','cancelled','abandoned'].map(status => <option key={status}>{status}</option>)}</select></label><label className="text-[14px] font-semibold text-text-secondary">Cost source<select aria-label="Usage cost source" className={selectClass} value={draft.costSource} onChange={e => setDraft({ ...draft, costSource: e.target.value })}><option value="">All sources</option><option value="provider_reported">Provider reported</option><option value="token_rate_estimate">Token-rate estimate</option><option value="unknown">Unknown</option></select></label>
  </DataTableToolbar>} columns={[
    { id: 'date', header: 'Started', cell: row => fmtDate(row.startedAt) }, { id: 'user', header: 'User', className: 'min-w-[200px] max-w-[260px]', cell: row => row.userId }, { id: 'category', header: 'Category', cell: row => categories[row.category] }, { id: 'status', header: 'Status', cell: row => row.status }, { id: 'cost', header: 'Observed cost', className: 'min-w-[180px]', cell: row => costLabel(row.cost) }, { id: 'build', header: 'Build / PR', className: 'min-w-[220px] max-w-[280px] break-all', cell: row => <>{row.buildSha ?? 'Build not recorded'}<p className="mt-[4px]">{row.buildPr === null ? 'PR not recorded' : `PR #${row.buildPr}`}</p></> }, { id: 'actions', header: 'Details', className: 'min-w-[260px]', cell: row => <div className="flex gap-[8px]"><Button variant="ghost" size="sm" aria-label={`Request ${row.id}`} onClick={() => setSelected({ id: row.id, conversation: false })}>Request</Button><Button variant="ghost" size="sm" disabled={!row.conversationId} aria-label={row.conversationId ? `Conversation ${row.conversationId}` : 'Conversation not recorded'} onClick={() => { if (row.conversationId) setSelected({ id: row.conversationId, conversation: true }) }}>Conversation</Button></div> },
  ]} />{selected && <UsageDetail key={`${selected.id}:${selected.conversation}`} selected={selected} close={() => setSelected(null)} />}</section>
}
export function AdminAiUsage() { const access = useAccess(); return access.actorCapabilities.canReadSharedConversations ? <UsageTable key={`${access.identity}:${access.revision}`} /> : <EmptyState icon="lock" title="AI usage unavailable" body="Administrative usage access is required." /> }
