import { useState } from 'react'
import { api } from '../../lib/api'
import { Button, DataTable, DataTableToolbar } from '../../components/ui'
import { useAdminQuery, selectClass } from './shared'
export function CostObservations({ onUse, canWrite }: { onUse: (operation: 'chatTurn' | 'analysis' | 'planDeck', microUsd: number) => void; canWrite: boolean }) {
  const [days, setDays] = useState('30'), [draftBuild, setDraftBuild] = useState(''), [buildSha, setBuildSha] = useState('')
  const params = new URLSearchParams({ days, ...(buildSha ? { buildSha } : {}) }).toString()
  const query = useAdminQuery(['cost-observations', params], signal => api.adminCostObservations(params, signal), 'admin.access')
  return <section className="min-w-0 space-y-[12px]"><h3 className="font-display text-[20px] text-text-primary">Observed provider costs</h3><p className="text-[14px] text-text-muted">Complete samples inform future estimates. Unknown or partial samples are excluded from mean and percentile. Choosing a mean only fills the draft below; Save credit economy creates the pricing revision.</p>{query.data && <p className="text-[13px] text-text-muted">{query.data.notice} Window: {query.data.days} days. {query.data.buildSha ? `Build ${query.data.buildSha}` : 'All recorded builds.'}</p>}<DataTable label="Observed operation costs" rows={query.data?.groups ?? []} getRowId={(group) => `${group.operation}:${group.buildSha}:${group.modelIds.join(',')}`} loading={query.isPending} refreshing={query.isFetching && !query.isPending} error={query.error?.message} onRetry={() => void query.refetch()} toolbar={<DataTableToolbar label="Filter cost observations" search={{ label: 'Observed build SHA', value: draftBuild, onChange: setDraftBuild }} onSubmit={() => setBuildSha(draftBuild.trim())} onReset={() => { setDraftBuild(''); setBuildSha(''); setDays('30') }}><label className="text-[14px] font-semibold text-text-secondary">Observation window<select aria-label="Observation window" className={selectClass} value={days} onChange={e => setDays(e.target.value)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label></DataTableToolbar>} columns={[
    { id: 'operation', header: 'Operation', cell: group => ({ chatTurn: 'Standard response', analysis: 'Research / analysis', planDeck: 'In-depth planning' })[group.operation] }, { id: 'sample', header: 'Samples', cell: group => `${group.completeCount} complete / ${group.sampleCount} recorded; ${group.unknownCount} unknown` }, { id: 'mean', header: 'Mean / p95 USD', cell: group => `${group.meanMicroUsd === null ? 'Unknown' : '$' + (group.meanMicroUsd / 1e6)} / ${group.p95MicroUsd === null ? 'Unknown' : '$' + (group.p95MicroUsd / 1e6)}` }, { id: 'build', header: 'Build / models', className: 'min-w-[240px] max-w-[340px] break-all', cell: group => <>{group.buildSha ?? 'Build not recorded'}<p>{group.modelIds.join(', ') || 'Model not recorded'}</p></> }, ...(canWrite ? [{ id: 'use', header: 'Draft estimate', cell: (group: NonNullable<typeof query.data>['groups'][number]) => <Button variant="ghost" size="sm" disabled={group.meanMicroUsd === null || !Number.isSafeInteger(group.meanMicroUsd)} onClick={() => { if (group.meanMicroUsd !== null) onUse(group.operation, group.meanMicroUsd) }}>Use mean in draft</Button> }] : []),
  ]} /></section>
}
