import { useState } from 'react'
import { StatTile, Button, Field, EmptyState } from '../../components/ui'
import { api } from '../../lib/api'
import { dollars } from '../../lib/creditMath'
import { Panel, useAdminQuery, LoadState, Paging, selectClass, fmtDate } from './shared'
export function CreditOperations() {
  const [days, setDays] = useState('30'), [status, setStatus] = useState(''), [user, setUser] = useState(''), [filter, setFilter] = useState(''), [offset, setOffset] = useState(0)
  const summary = useAdminQuery(['credit-summary', days], signal => api.adminCreditSummary(Number(days), signal), 'credits.read')
  const params = new URLSearchParams({ status, user: filter, offset: String(offset), limit: '25' })
  const orders = useAdminQuery(['credit-orders', params.toString()], signal => api.adminCreditOrders(params.toString(), signal), 'credits.read')
  return <div className="space-y-[20px]"><Panel title="Credit activity"><label className="mb-[16px] block max-w-[220px] text-[14px] font-semibold text-text-secondary">Reporting window<select aria-label="Reporting window" className={selectClass + ' mt-[6px]'} value={days} onChange={e => setDays(e.target.value)}>{[7,30,90].map(d => <option key={d} value={d}>Last {d} days</option>)}</select></label><LoadState loading={summary.isLoading} error={summary.error} retry={summary.refetch} />
    {summary.data && <><div className="grid grid-cols-2 gap-[12px] xl:grid-cols-4"><StatTile variant="boxed" label="Credits spent" value={summary.data.creditsSpent.toLocaleString()} /><StatTile variant="boxed" label="Credits granted" value={summary.data.creditsGranted.toLocaleString()} /><StatTile variant="boxed" label="Gross pack sales" value={dollars(summary.data.grossSalesCents)} /><StatTile variant="boxed" label="Refunds on these purchases" value={dollars(summary.data.refundedCents)} /></div><p className="mt-[16px] text-[14px] text-text-muted">{summary.data.paidOrders} paid orders in this window. Current state: {summary.data.pendingOrders} pending orders · {summary.data.heldWallets} held wallets · {summary.data.debtWallets} wallets owing {summary.data.totalDebt} credits.</p><p className="mt-[8px] text-[14px] text-text-muted">Estimated provider cost for priced usage: {dollars(summary.data.estimatedProviderMicroUsd / 10000)}. This is an estimate, not actual provider billing or realized profit. {summary.data.unpricedSpends} historical spends lack a pricing snapshot.</p></>}
    </Panel><Panel title="Credit orders"><form onSubmit={e => { e.preventDefault(); setFilter(user); setOffset(0) }} className="grid items-end gap-[12px] sm:grid-cols-[2fr_1fr_auto]"><Field label="User ID" value={user} onChange={e => setUser(e.target.value)} maxLength={100} /><label className="mb-[16px] text-[14px] font-semibold text-text-secondary">Order status<select aria-label="Order status" className={selectClass + ' mt-[6px]'} value={status} onChange={e => { setStatus(e.target.value); setOffset(0) }}><option value="">All statuses</option>{['pending','paid','expired','refunded','disputed'].map(s => <option key={s} value={s}>{s}</option>)}</select></label><Button type="submit" className="mb-[16px]">Filter orders</Button></form><LoadState loading={orders.isLoading} error={orders.error} retry={orders.refetch} />
    {orders.data && <>{!orders.data.orders.length && <EmptyState icon="lists" title="No matching orders" body="Credit purchases will appear here." />}<ol className="divide-y divide-border-default">{orders.data.orders.map(order => <li key={order.id} className="py-[14px]"><div className="flex flex-wrap justify-between gap-[8px]"><strong className="break-words text-text-primary">{order.packName} · {order.status}</strong><span className="text-text-body">{order.credits} credits · {dollars(order.priceCents)}</span></div><p className="mt-[6px] break-all text-[14px] text-text-muted">{order.username ?? order.userId} · {fmtDate(order.createdAt)}</p><p className="mt-[4px] break-all text-[12px] text-text-muted">Order {order.id}</p>{(order.refundedCents > 0 || order.disputeStatus) && <p className="mt-[6px] text-[14px] text-text-muted">{dollars(order.refundedCents)} refunded · {order.reversedCredits} credits reversed{order.disputeStatus ? ' · Dispute: ' + order.disputeStatus : ''}</p>}</li>)}</ol><Paging total={orders.data.total} offset={offset} setOffset={setOffset} /></>}</Panel>
  </div>
}
