import { useState } from 'react'
import { api } from '../../lib/api'
import { useAccess, invalidateAccess } from '../../lib/access'
import type { FeatureAccess } from '../../lib/adminTypes'
import { Button, DataTable, EmptyState, Field, FormAlert } from '../../components/ui'
import { Sheet } from '../../components/ui/Sheet'
import { useAdminQuery, useAdminSave, selectClass } from './shared'
function LifecycleEditor({ feature, close }: { feature: FeatureAccess; close: () => void }) {
  const [lifecycle, setLifecycle] = useState(feature.lifecycle), [reason, setReason] = useState(''), state = useAdminSave()
  return <Sheet title={`Configure ${feature.label}`} onClose={() => { if (state.busy) return false; close() }}><form className="space-y-[16px]" onSubmit={e => { e.preventDefault(); void state.save(() => api.adminSetFeature(feature.key, lifecycle, feature.revision, reason.trim()), () => { close(); invalidateAccess() }) }}><label className="block font-semibold text-text-secondary">Release stage<select aria-label="Feature release stage" className={selectClass + ' mt-[6px]'} value={lifecycle} onChange={e => setLifecycle(e.target.value as FeatureAccess['lifecycle'])}><option value="released">Released</option><option value="beta">Beta</option><option value="experimental">Experimental</option><option value="disabled">Disabled</option></select></label><p className="text-text-muted">Released is available to active users. Beta requires opt-in. Experiments allow every Superuser, Contributor and Admin to opt in; Superadmin and Owner access is automatic. Disabled blocks new use for everyone. Work already sent to a provider may finish.</p><Field label="Reason" value={reason} onChange={e => setReason(e.target.value)} required minLength={3} maxLength={500} />{state.error && <FormAlert kind="error">{state.error}</FormAlert>}<Button type="submit" loading={state.busy}>Save feature lifecycle</Button></form></Sheet>
}
function FeatureCatalog() {
  const query = useAdminQuery(['features'], signal => api.adminFeatures(signal), 'admin.access'), [editing, setEditing] = useState<FeatureAccess | null>(null)
  return <section className="space-y-[20px]"><h2 className="font-display text-[24px] text-text-primary">Feature lifecycle</h2><p className="text-text-muted">Superadmins and Owners configure product release stages. Individual opt-ins remain separate from conversation sharing.</p><DataTable label="Feature lifecycle catalog" rows={query.data?.features ?? []} getRowId={f => f.key} loading={query.isPending} refreshing={query.isFetching && !query.isPending} error={query.error?.message} onRetry={() => void query.refetch()} columns={[{ id: 'name', header: 'Feature', cell: f => f.label }, { id: 'stage', header: 'Release stage', cell: f => f.lifecycle }, { id: 'revision', header: 'Revision', cell: f => f.revision }, { id: 'actions', header: 'Actions', cell: f => <Button size="sm" variant="ghost" aria-label={`Configure ${f.label}`} onClick={() => setEditing(f)}>Configure</Button> }]} />{editing && <LifecycleEditor feature={editing} close={() => setEditing(null)} />}</section>
}
export function AdminFeatures() { const access = useAccess(); return access.actorCapabilities.canEditRoles ? <FeatureCatalog key={access.revision} /> : <EmptyState icon="lock" title="Feature configuration unavailable" body="Only Superadmins and Owners can change release stages." /> }
