// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "me02-087": {
  "cardId": "me02-087",
  "name": "Dawn",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for a Basic Pokémon, a Stage 1 Pokémon, and a Stage 2 Pokémon, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-024": {
  "cardId": "sv09-024",
  "name": "Blaziken ex",
  "category": "Pokemon",
  "hp": 320,
  "stage": "Stage2",
  "suffix": "ex",
  "evolvesFrom": "Combusken",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Smolder-sault",
    "cost": "Fire,Colorless",
    "damage": "200",
    "effect": "During your next turn, this Pokémon can't attack."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Seething Spirit",
    "effect": "Once during your turn, you may attach a Basic Energy card from your discard pile to 1 of your Pokémon."
   }
  ],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-056": {
  "cardId": "sv09-056",
  "name": "Lillie's Clefairy ex",
  "category": "Pokemon",
  "hp": 190,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Full Moon Rondo",
    "cost": "Psychic,Colorless",
    "damage": "20+",
    "effect": "This attack does 20 more damage for each Benched Pokémon (both yours and your opponent's)."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Fairy Zone",
    "effect": "The Weakness of each of your opponent's {N} Pokémon in play is now {P}. (Apply Weakness as ×2.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Metal",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv10-040": {
  "cardId": "sv10-040",
  "name": "Torchic",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Collect",
    "cost": "Colorless",
    "damage": null,
    "effect": "Draw a card."
   },
   {
    "name": "Combustion",
    "cost": "Fire",
    "damage": "10",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv10-041": {
  "cardId": "sv10-041",
  "name": "Combusken",
  "category": "Pokemon",
  "hp": 100,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Torchic",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Combustion",
    "cost": "Colorless",
    "damage": "20",
    "effect": null
   },
   {
    "name": "Double Kick",
    "cost": "Fire,Colorless",
    "damage": "40×",
    "effect": "Flip 2 coins. This attack does 40 damage for each heads."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 }
};
