// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "30th-013": {
  "cardId": "30th-013",
  "name": "Victini",
  "category": "Pokemon",
  "hp": 80,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Call for Family",
    "cost": "Colorless",
    "damage": null,
    "effect": "Search your deck for up to 2 Basic Pokémon and put them onto your Bench. Then, shuffle your deck."
   },
   {
    "name": "V-Flame",
    "cost": "Fire,Colorless",
    "damage": "50",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me01-114": {
  "cardId": "me01-114",
  "name": "Boss's Orders",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Switch in 1 of your opponent's Benched Pokémon to the Active Spot.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me01-119": {
  "cardId": "me01-119",
  "name": "Lillie's Determination",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Shuffle your hand into your deck. Then, draw 6 cards. If you have exactly 6 Prize cards remaining, draw 8 cards instead.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me01-125": {
  "cardId": "me01-125",
  "name": "Rare Candy",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Choose 1 of your Basic Pokémon in play. If you have a Stage 2 card in your hand that evolves from that Pokémon, put that card onto the Basic Pokémon to evolve it, skipping the Stage 1. You can't use this card during your first turn or on a Basic Pokémon that was put into play this turn.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me01-130": {
  "cardId": "me01-130",
  "name": "Switch",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Switch your Active Pokémon with 1 of your Benched Pokémon.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02-011": {
  "cardId": "me02-011",
  "name": "Charmander",
  "category": "Pokemon",
  "hp": 80,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Live Coal",
    "cost": "Fire",
    "damage": "20",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Agile",
    "effect": "If this Pokémon has no Energy attached, it has no Retreat Cost."
   }
  ],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02-012": {
  "cardId": "me02-012",
  "name": "Charmeleon",
  "category": "Pokemon",
  "hp": 110,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Charmander",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Steady Firebreathing",
    "cost": "Fire",
    "damage": "40",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02-013": {
  "cardId": "me02-013",
  "name": "Mega Charizard X ex",
  "category": "Pokemon",
  "hp": 360,
  "stage": "Stage2",
  "suffix": "ex",
  "evolvesFrom": "Charmeleon",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Inferno X",
    "cost": "Fire,Fire",
    "damage": "90×",
    "effect": "Discard any amount of {R} Energy from among your Pokémon, and this attack does 90 damage for each card you discarded in this way."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02-018": {
  "cardId": "me02-018",
  "name": "Oricorio ex",
  "category": "Pokemon",
  "hp": 190,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Fire Wing",
    "cost": "Fire,Fire,Colorless",
    "damage": "110",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Excited Turbo",
    "effect": "As often as you like during your turn, if you have any {R} Mega Evolution Pokémon ex in play, you may use this Ability. Attach a Basic {R} Energy card from your hand to 1 of your Benched {R} Pokémon."
   }
  ],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02-085": {
  "cardId": "me02-085",
  "name": "Battle Cage",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Prevent all damage counters from being placed on Benched Pokémon (both yours and your opponent's) by effects of attacks and Abilities from the opponent's Pokémon. (Damage from attacks is still taken.)",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02-086": {
  "cardId": "me02-086",
  "name": "Blowtorch",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "You can use this card only if you discard a Basic {R} Energy card from your hand.\n\nDiscard a Pokémon Tool or Special Energy card from 1 of your opponent's Pokémon, or discard a Stadium in play.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02-087": {
  "cardId": "me02-087",
  "name": "Dawn",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for a Basic Pokémon, a Stage 1 Pokémon, and a Stage 2 Pokémon, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02-089": {
  "cardId": "me02-089",
  "name": "Firebreather",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 7 Basic {R} Energy cards, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02.5-016": {
  "cardId": "me02.5-016",
  "name": "Budew",
  "category": "Pokemon",
  "hp": 30,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 0,
  "types": [
   "Grass"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Itchy Pollen",
    "cost": null,
    "damage": "10",
    "effect": "During your opponent's next turn, they can't play any Item cards from their hand."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02.5-142": {
  "cardId": "me02.5-142",
  "name": "Fezandipiti ex",
  "category": "Pokemon",
  "hp": 210,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Cruel Arrow",
    "cost": "Colorless,Colorless,Colorless",
    "damage": null,
    "effect": "This attack does 100 damage to 1 of your opponent's Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)"
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Flip the Script",
    "effect": "Once during your turn, if any of your Pokémon were Knocked Out during your opponent's last turn, you may draw 3 cards. You can't use more than 1 Flip the Script Ability each turn."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02.5-181": {
  "cardId": "me02.5-181",
  "name": "Air Balloon",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "The Retreat Cost of the Pokémon this card is attached to is {C}{C} less.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02.5-196": {
  "cardId": "me02.5-196",
  "name": "Night Stretcher",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Put a Pokémon or a Basic Energy card from your discard pile into your hand.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me03-062": {
  "cardId": "me03-062",
  "name": "Meowth ex",
  "category": "Pokemon",
  "hp": 170,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Tuck Tail",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "60",
    "effect": "Put this Pokémon and all attached cards into your hand."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Last-Ditch Catch",
    "effect": "Once during your turn, when you play this Pokémon from your hand onto your Bench, you may use this Ability. Search your deck for a Supporter card, reveal it, and put it into your hand. Then, shuffle your deck. You can't use more than 1 Ability that has \"Last-Ditch\" in its name each turn."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me03-081": {
  "cardId": "me03-081",
  "name": "Poké Pad",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for a Pokémon that doesn't have a Rule Box, reveal it, and put it into your hand. Then, shuffle your deck. (Pokémon ex, Pokémon V, etc. have Rule Boxes.)",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me04-009": {
  "cardId": "me04-009",
  "name": "Ninetales",
  "category": "Pokemon",
  "hp": 120,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Vulpix",
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Nine-Tailed Transfer",
    "cost": "Fire",
    "damage": null,
    "effect": "Move all damage counters from 1 of your Benched Pokémon to your opponent's Active Pokémon."
   },
   {
    "name": "Will-O-Wisp",
    "cost": "Fire,Fire",
    "damage": "70",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "mee-010": {
  "cardId": "mee-010",
  "name": "Basic Fire Energy",
  "category": "Energy",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": "Normal",
  "retreat": null,
  "types": [],
  "effect": null,
  "regulationMark": null,
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv01-171": {
  "cardId": "sv01-171",
  "name": "Energy Retrieval",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Put up to 2 Basic Energy cards from your discard pile into your hand.",
  "regulationMark": "G",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06.5-063": {
  "cardId": "sv06.5-063",
  "name": "Powerglass",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "At the end of your turn (after your attack), if the Pokémon this card is attached to is in the Active Spot, you may attach a Basic Energy card from your discard pile to it.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv08-016": {
  "cardId": "sv08-016",
  "name": "Vulpix",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Take Down",
    "cost": "Fire",
    "damage": "30",
    "effect": "This Pokémon also does 10 damage to itself."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv08-185": {
  "cardId": "sv08-185",
  "name": "Precious Trolley",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for any number of Basic Pokémon and put them onto your Bench. Then, shuffle your deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-146": {
  "cardId": "sv09-146",
  "name": "Brock's Scouting",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 2 Basic Pokémon or 1 Evolution Pokémon, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv10-164": {
  "cardId": "sv10-164",
  "name": "Energy Recycler",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Shuffle up to 5 Basic Energy cards from your discard pile into your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv10-176": {
  "cardId": "sv10-176",
  "name": "Team Rocket's Petrel",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for a Trainer card, reveal it, and put it into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 }
};
