// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "me01-121": {
  "cardId": "me01-121",
  "name": "Mega Signal",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for a Mega Evolution Pokémon ex, reveal it, and put it into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me02-085": {
  "cardId": "me02-085",
  "name": "Battle Cage",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Prevent all damage counters from being placed on Benched Pokémon (both yours and your opponent's) by effects of attacks and Abilities from the opponent's Pokémon. (Damage from attacks is still taken.)",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me05-048": {
  "cardId": "me05-048",
  "name": "Mega Darkrai ex",
  "category": "Pokemon",
  "hp": 280,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Dusk Raid",
    "cost": "Darkness,Darkness",
    "damage": "110+",
    "effect": "If your Benched Pokémon have any damage counters on them, this attack does 110 more damage."
   },
   {
    "name": "Abyss Eye",
    "cost": "Darkness,Darkness,Darkness",
    "damage": null,
    "effect": "If your opponent's Active Pokémon is affected by a Special Condition, it is Knocked Out."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Grass",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me05-075": {
  "cardId": "me05-075",
  "name": "Dark Bell",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Both Active non-{D} Pokémon are now Confused.",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv01-186": {
  "cardId": "sv01-186",
  "name": "Pokégear 3.0",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Look at the top 7 cards of your deck. You may reveal a Supporter card you find there and put it into your hand. Shuffle the other cards back into your deck.",
  "regulationMark": "G",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv05-145": {
  "cardId": "sv05-145",
  "name": "Ciphermaniac's Codebreaking",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for 2 cards, shuffle your deck, then put those cards on top of it in any order.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv08-170": {
  "cardId": "sv08-170",
  "name": "Cyrano",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 3 Pokémon ex, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv08-180": {
  "cardId": "sv08-180",
  "name": "Lively Stadium",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Each Basic Pokémon in play (both yours and your opponent's) gets +30 HP.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv08.5-112": {
  "cardId": "sv08.5-112",
  "name": "Janine's Secret Art",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Choose up to 2 of your {D} Pokémon. For each of those Pokémon, search your deck for a Basic {D} Energy card and attach it to that Pokémon. Then, shuffle your deck. If you attached Energy to your Active Pokémon in this way, it is now Poisoned.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-031": {
  "cardId": "sv09-031",
  "name": "Volcanion ex",
  "category": "Pokemon",
  "hp": 220,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Scorching Cyclone",
    "cost": "Fire,Fire,Colorless",
    "damage": "160",
    "effect": "Move an Energy from this Pokémon to 1 of your Benched Pokémon."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Scalding Steam",
    "effect": "Once during your turn, if this Pokémon is in the Active Spot, you may make your opponent's Active Pokémon Burned."
   }
  ],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 }
};
