// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "me02-027": {
  "cardId": "me02-027",
  "name": "Piplup",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Water"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Call for Support",
    "cost": "Colorless",
    "damage": null,
    "effect": "Search your deck for a Supporter card, reveal it, and put it into your hand. Then, shuffle your deck."
   },
   {
    "name": "Tackle",
    "cost": "Colorless,Colorless",
    "damage": "20",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Lightning",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "me02-070": {
  "cardId": "me02-070",
  "name": "Empoleon ex",
  "category": "Pokemon",
  "hp": 320,
  "stage": "Stage2",
  "suffix": "ex",
  "evolvesFrom": "Prinplup",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Metal"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Iron Feathers",
    "cost": "Metal,Metal,Colorless",
    "damage": "210",
    "effect": "During your opponent's next turn, this Pokémon takes 60 less damage from attacks (after applying Weakness and Resistance)."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Emperor's Stance",
    "effect": "Prevent all effects of attacks used by your opponent's Pokémon done to this Pokémon. (Damage is not an effect.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Grass",
    "value": "-30"
   }
  ]
 },
 "me05-046": {
  "cardId": "me05-046",
  "name": "Drilbur",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fighting"
  ],
  "effect": null,
  "regulationMark": "J",
  "attacks": [
   {
    "name": "Call for Family",
    "cost": "Colorless",
    "damage": null,
    "effect": "Search your deck for up to 2 Basic Pokémon and put them onto your Bench. Then, shuffle your deck."
   },
   {
    "name": "Dig Claws",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "50",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Grass",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv01-186": {
  "cardId": "sv01-186",
  "name": "Pokégear 3.0",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Look at the top 7 cards of your deck. You may reveal a Supporter card you find there and put it into your hand. Shuffle the other cards back into your deck.",
  "regulationMark": "G",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv05-113": {
  "cardId": "sv05-113",
  "name": "Beldum",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Metal"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Dig Claws",
    "cost": "Metal",
    "damage": "10",
    "effect": null
   },
   {
    "name": "Iron Tackle",
    "cost": "Metal,Colorless,Colorless",
    "damage": "50",
    "effect": "This Pokémon also does 10 damage to itself."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Grass",
    "value": "-30"
   }
  ]
 },
 "sv05-114": {
  "cardId": "sv05-114",
  "name": "Metang",
  "category": "Pokemon",
  "hp": 100,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Beldum",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Metal"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Beam",
    "cost": "Metal,Colorless,Colorless",
    "damage": "60",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Metal Maker",
    "effect": "Once during your turn, you may look at the top 4 cards of your deck and attach any number of Basic {M} Energy cards you find there to your Pokémon in any way you like. Shuffle the other cards and put them on the bottom of your deck."
   }
  ],
  "weaknesses": [
   {
    "type": "Fire",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Grass",
    "value": "-30"
   }
  ]
 },
 "sv05-152": {
  "cardId": "sv05-152",
  "name": "Hero's Cape",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "The Pokémon this card is attached to gets +100 HP.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06-154": {
  "cardId": "sv06-154",
  "name": "Kieran",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Choose 1:\n\n• Switch your Active Pokémon with 1 of your Benched Pokémon.\n\n• During this turn, attacks used by your Pokémon do 30 more damage to your opponent's Active Pokémon ex and Active Pokémon V (before applying Weakness and Resistance).",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-146": {
  "cardId": "sv09-146",
  "name": "Brock's Scouting",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 2 Basic Pokémon or 1 Evolution Pokémon, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 }
};
