// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "me01-088": {
  "cardId": "me01-088",
  "name": "Yveltal",
  "category": "Pokemon",
  "hp": 110,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 0,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Clutch",
    "cost": "Darkness",
    "damage": "20",
    "effect": "During your opponent's next turn, the Defending Pokémon can't retreat."
   },
   {
    "name": "Dark Feather",
    "cost": "Darkness,Darkness,Colorless",
    "damage": "110",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Lightning",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me02.5-181": {
  "cardId": "me02.5-181",
  "name": "Air Balloon",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "The Retreat Cost of the Pokémon this card is attached to is {C}{C} less.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06-131": {
  "cardId": "sv06-131",
  "name": "Tatsugiri",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Dragon"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Surf",
    "cost": "Fire,Water",
    "damage": "50",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Attract Customers",
    "effect": "Once during your turn, if this Pokémon is in the Active Spot, you may look at the top 6 cards of your deck, reveal a Supporter card you find there, and put it into your hand. Shuffle the other cards back into your deck."
   }
  ],
  "weaknesses": [],
  "resistances": []
 },
 "sv10-134": {
  "cardId": "sv10-134",
  "name": "Marnie's Impidimp",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Filch",
    "cost": "Colorless",
    "damage": null,
    "effect": "Draw a card."
   },
   {
    "name": "Corkscrew Punch",
    "cost": "Darkness",
    "damage": "10",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Grass",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv10-135": {
  "cardId": "sv10-135",
  "name": "Marnie's Morgrem",
  "category": "Pokemon",
  "hp": 100,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Marnie's Impidimp",
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Corkscrew Punch",
    "cost": "Darkness,Darkness",
    "damage": "60",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Grass",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv10-136": {
  "cardId": "sv10-136",
  "name": "Marnie's Grimmsnarl ex",
  "category": "Pokemon",
  "hp": 320,
  "stage": "Stage2",
  "suffix": "ex",
  "evolvesFrom": "Marnie's Morgrem",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Shadow Bullet",
    "cost": "Darkness,Darkness",
    "damage": "180",
    "effect": "This attack also does 30 damage to 1 of your opponent's Benched Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)"
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Punk Up",
    "effect": "When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may search your deck for up to 5 Basic {D} Energy cards and attach them to your Marnie's Pokémon in any way you like. Then, shuffle your deck."
   }
  ],
  "weaknesses": [
   {
    "type": "Grass",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv10-169": {
  "cardId": "sv10-169",
  "name": "Spikemuth Gym",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Once during each player's turn, that player may search their deck for a Marnie's Pokémon, reveal it, and put it into their hand. Then, that player shuffles their deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 }
};
