// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "me02.5-095": {
  "cardId": "me02.5-095",
  "name": "Hop's Phantump",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Splashing Dodge",
    "cost": "Colorless",
    "damage": "10",
    "effect": "Flip a coin. If heads, during your opponent's next turn, prevent all damage from and effects of attacks done to this Pokémon."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me02.5-096": {
  "cardId": "me02.5-096",
  "name": "Hop's Trevenant",
  "category": "Pokemon",
  "hp": 140,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Hop's Phantump",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Horrifying Revenge",
    "cost": "Colorless",
    "damage": "30+",
    "effect": "If any of your Hop's Pokémon were Knocked Out by damage from an attack during your opponent's last turn, this attack does 100 more damage."
   },
   {
    "name": "Corner",
    "cost": "Psychic,Colorless,Colorless",
    "damage": "90",
    "effect": "During your opponent's next turn, the Defending Pokémon can't retreat."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Darkness",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me02.5-181": {
  "cardId": "me02.5-181",
  "name": "Air Balloon",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "The Retreat Cost of the Pokémon this card is attached to is {C}{C} less.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv05-161": {
  "cardId": "sv05-161",
  "name": "Mist Energy",
  "category": "Energy",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": "Special",
  "retreat": null,
  "types": [],
  "effect": "As long as this card is attached to a Pokémon, it provides {C} Energy.\n\nPrevent all effects of attacks used by your opponent's Pokémon done to the Pokémon this card is attached to. (Existing effects are not removed. Damage is not an effect.)",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06-151": {
  "cardId": "sv06-151",
  "name": "Hassel",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "You can use this card only if any of your Pokémon were Knocked Out during your opponent's last turn.\n\nLook at the top 8 cards of your deck and put up to 3 of them into your hand. Shuffle the other cards back into your deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-056": {
  "cardId": "sv09-056",
  "name": "Lillie's Clefairy ex",
  "category": "Pokemon",
  "hp": 190,
  "stage": "Basic",
  "suffix": "ex",
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Psychic"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Full Moon Rondo",
    "cost": "Psychic,Colorless",
    "damage": "20+",
    "effect": "This attack does 20 more damage for each Benched Pokémon (both yours and your opponent's)."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Fairy Zone",
    "effect": "The Weakness of each of your opponent's {N} Pokémon in play is now {P}. (Apply Weakness as ×2.)"
   }
  ],
  "weaknesses": [
   {
    "type": "Metal",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-117": {
  "cardId": "sv09-117",
  "name": "Hop's Snorlax",
  "category": "Pokemon",
  "hp": 150,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 4,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Dynamic Press",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "140",
    "effect": "This Pokémon also does 80 damage to itself."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Extra Helpings",
    "effect": "Attacks used by your Hop's Pokémon do 30 more damage to your opponent's Active Pokémon (before applying Weakness and Resistance). The effect of Extra Helpings doesn't stack."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-135": {
  "cardId": "sv09-135",
  "name": "Hop's Wooloo",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Smash Kick",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "50",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-136": {
  "cardId": "sv09-136",
  "name": "Hop's Dubwool",
  "category": "Pokemon",
  "hp": 120,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "Hop's Wooloo",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Headbutt",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "80",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Defiant Horn",
    "effect": "When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may switch in 1 of your opponent's Benched Pokémon to the Active Spot."
   }
  ],
  "weaknesses": [
   {
    "type": "Fighting",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-138": {
  "cardId": "sv09-138",
  "name": "Hop's Cramorant",
  "category": "Pokemon",
  "hp": 110,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Colorless"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Fickle Spitting",
    "cost": "Colorless",
    "damage": "120",
    "effect": "If your opponent doesn't have exactly 3 or 4 Prize cards remaining, this attack does nothing."
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Lightning",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "sv09-147": {
  "cardId": "sv09-147",
  "name": "Hop's Bag",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 2 Basic Hop's Pokémon and put them onto your Bench. Then, shuffle your deck.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-148": {
  "cardId": "sv09-148",
  "name": "Hop's Choice Band",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Attacks used by the Hop's Pokémon this card is attached to cost {C} less and do 30 more damage to your opponent's Active Pokémon (before applying Weakness and Resistance).",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-154": {
  "cardId": "sv09-154",
  "name": "Postwick",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Attacks used by Hop's Pokémon (both yours and your opponent's) do 30 more damage to the opponent's Active Pokémon (before applying Weakness and Resistance).",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-157": {
  "cardId": "sv09-157",
  "name": "Ruffian",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Discard a Pokémon Tool and a Special Energy from 1 of your opponent's Pokémon.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 }
};
