// GENERATED by scripts/fetch-frames.mjs from the DeckPal catalog. Do not edit by hand.
import type { CardFrame } from '../../types.js';

export const FRAMES: Record<string, CardFrame> = {
 "me01-088": {
  "cardId": "me01-088",
  "name": "Yveltal",
  "category": "Pokemon",
  "hp": 110,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 0,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Clutch",
    "cost": "Darkness",
    "damage": "20",
    "effect": "During your opponent's next turn, the Defending Pokémon can't retreat."
   },
   {
    "name": "Dark Feather",
    "cost": "Darkness,Darkness,Colorless",
    "damage": "110",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Lightning",
    "value": "×2"
   }
  ],
  "resistances": [
   {
    "type": "Fighting",
    "value": "-30"
   }
  ]
 },
 "me02.5-155": {
  "cardId": "me02.5-155",
  "name": "N's Zekrom",
  "category": "Pokemon",
  "hp": 130,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Dragon"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Shred",
    "cost": "Colorless,Colorless,Colorless",
    "damage": "70",
    "effect": "This attack's damage isn't affected by any effects on your opponent's Active Pokémon."
   },
   {
    "name": "Rampaging Thunder",
    "cost": "Fire,Lightning,Lightning,Colorless",
    "damage": "250",
    "effect": "During your next turn, this Pokémon can't use attacks."
   }
  ],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "me04-083": {
  "cardId": "me04-083",
  "name": "Transformation Tome",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "You must play 2 Transformation Tome cards at once. (This effect works one time for 2 cards.)\n\nChoose a Basic Pokémon in your discard pile and switch it with 1 of your Basic Pokémon in play. Any attached cards, damage counters, Special Conditions, turns in play, and any other effects remain on the new Pokémon.",
  "regulationMark": "J",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "mee-015": {
  "cardId": "mee-015",
  "name": "Basic Darkness Energy",
  "category": "Energy",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": "Normal",
  "retreat": null,
  "types": [],
  "effect": null,
  "regulationMark": null,
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv05-145": {
  "cardId": "sv05-145",
  "name": "Ciphermaniac's Codebreaking",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for 2 cards, shuffle your deck, then put those cards on top of it in any order.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv06-131": {
  "cardId": "sv06-131",
  "name": "Tatsugiri",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Dragon"
  ],
  "effect": null,
  "regulationMark": "H",
  "attacks": [
   {
    "name": "Surf",
    "cost": "Fire,Water",
    "damage": "50",
    "effect": null
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Attract Customers",
    "effect": "Once during your turn, if this Pokémon is in the Active Spot, you may look at the top 6 cards of your deck, reveal a Supporter card you find there, and put it into your hand. Shuffle the other cards back into your deck."
   }
  ],
  "weaknesses": [],
  "resistances": []
 },
 "sv06-164": {
  "cardId": "sv06-164",
  "name": "Survival Brace",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Tool",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "If the Pokémon this card is attached to has full HP and would be Knocked Out by damage from an attack from your opponent's Pokémon, it is not Knocked Out, and its remaining HP becomes 10. Then, discard this card.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv08-170": {
  "cardId": "sv08-170",
  "name": "Cyrano",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Search your deck for up to 3 Pokémon ex, reveal them, and put them into your hand. Then, shuffle your deck.",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-026": {
  "cardId": "sv09-026",
  "name": "N's Darumaka",
  "category": "Pokemon",
  "hp": 80,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Rolling Tackle",
    "cost": "Colorless,Colorless",
    "damage": "20",
    "effect": null
   },
   {
    "name": "Flare",
    "cost": "Fire,Fire,Colorless",
    "damage": "50",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-027": {
  "cardId": "sv09-027",
  "name": "N's Darmanitan",
  "category": "Pokemon",
  "hp": 140,
  "stage": "Stage1",
  "suffix": null,
  "evolvesFrom": "N's Darumaka",
  "trainerType": null,
  "energyType": null,
  "retreat": 3,
  "types": [
   "Fire"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Back Draft",
    "cost": "Colorless,Colorless",
    "damage": "30×",
    "effect": "This attack does 30 damage for each Basic Energy card in your opponent's discard pile."
   },
   {
    "name": "Flamebody Cannon",
    "cost": "Fire,Fire,Colorless",
    "damage": "90",
    "effect": "Discard all Energy from this Pokémon, and this attack also does 90 damage to 1 of your opponent's Benched Pokémon. (Don't apply Weakness and Resistance for Benched Pokémon.)"
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Water",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-097": {
  "cardId": "sv09-097",
  "name": "N's Zorua",
  "category": "Pokemon",
  "hp": 70,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 1,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Scratch",
    "cost": "Darkness",
    "damage": "20",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [
   {
    "type": "Grass",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-098": {
  "cardId": "sv09-098",
  "name": "N's Zoroark ex",
  "category": "Pokemon",
  "hp": 280,
  "stage": "Stage1",
  "suffix": "ex",
  "evolvesFrom": "N's Zorua",
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Darkness"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Night Joker",
    "cost": "Darkness,Darkness",
    "damage": null,
    "effect": "Choose 1 of your Benched N's Pokémon's attacks and use it as this attack."
   }
  ],
  "abilities": [
   {
    "kind": "Ability",
    "name": "Trade",
    "effect": "You must discard a card from your hand in order to use this Ability. Once during your turn, you may draw 2 cards."
   }
  ],
  "weaknesses": [
   {
    "type": "Grass",
    "value": "×2"
   }
  ],
  "resistances": []
 },
 "sv09-116": {
  "cardId": "sv09-116",
  "name": "N's Reshiram",
  "category": "Pokemon",
  "hp": 130,
  "stage": "Basic",
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": null,
  "energyType": null,
  "retreat": 2,
  "types": [
   "Dragon"
  ],
  "effect": null,
  "regulationMark": "I",
  "attacks": [
   {
    "name": "Powerful Rage",
    "cost": "Fire,Lightning",
    "damage": "20×",
    "effect": "This attack does 20 damage for each damage counter on this Pokémon."
   },
   {
    "name": "Virtuous Flame",
    "cost": "Fire,Fire,Lightning,Colorless",
    "damage": "170",
    "effect": null
   }
  ],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-143": {
  "cardId": "sv09-143",
  "name": "Black Belt's Training",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Supporter",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "During this turn, attacks used by your Pokémon do 40 more damage to your opponent's Active Pokémon ex (before applying Weakness and Resistance).",
  "regulationMark": "H",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-152": {
  "cardId": "sv09-152",
  "name": "N's Castle",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Stadium",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "N's Pokémon in play (both yours and your opponent's) have no Retreat Cost.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 },
 "sv09-153": {
  "cardId": "sv09-153",
  "name": "N's PP Up",
  "category": "Trainer",
  "hp": null,
  "stage": null,
  "suffix": null,
  "evolvesFrom": null,
  "trainerType": "Item",
  "energyType": null,
  "retreat": null,
  "types": [],
  "effect": "Attach a Basic Energy card from your discard pile to 1 of your Benched N's Pokémon.",
  "regulationMark": "I",
  "attacks": [],
  "abilities": [],
  "weaknesses": [],
  "resistances": []
 }
};
