import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import assert from 'node:assert/strict'
import { test } from 'node:test'

import { EMBED_SPEC_VERSION, embedInput } from '../input-spec.js'
import { PARITY_CASES, syntheticRgba } from './fixtures.js'

// The TypeScript half of the cross-runtime bit-parity contract. The Python half
// is `python/tests/test_parity.py`, and both check the SAME committed digest —
// which is the only arrangement in which either of them means anything. A test
// that compared TypeScript against a golden TypeScript wrote would pass forever
// while the two implementations drifted apart.

const HERE = dirname(fileURLToPath(import.meta.url))
const GOLDEN = JSON.parse(
  readFileSync(join(HERE, '..', '..', 'fixtures', 'parity-golden.json'), 'utf8'),
) as {
  specVersion: number
  size: number
  cases: { name: string; sha256: string; length: number; first8: number[]; last8: number[] }[]
}

test('the golden was generated by THIS spec version', () => {
  // If these disagree the golden is stale, and every other assertion in this
  // file would be checking the implementation against its own past.
  assert.equal(GOLDEN.specVersion, EMBED_SPEC_VERSION)
})

for (const c of PARITY_CASES) {
  test(`${c.name} matches the committed golden digest`, () => {
    const golden = GOLDEN.cases.find((g) => g.name === c.name)
    assert.ok(golden, `no golden case named ${c.name} — regenerate with gen-golden.ts`)
    const data = syntheticRgba(c.seed, c.width, c.height)
    const t = embedInput({ width: c.width, height: c.height, data }, { marginFrac: c.marginFrac })
    assert.equal(t.length, golden.length)
    // Sample values first: when this fails, the digest line below fails too and
    // says nothing, while these say WHERE.
    assert.deepEqual(Array.from(t.slice(0, 8)), golden.first8)
    assert.deepEqual(Array.from(t.slice(-8)), golden.last8)
    const sha = createHash('sha256')
      .update(Buffer.from(t.buffer, t.byteOffset, t.byteLength))
      .digest('hex')
    assert.equal(sha, golden.sha256)
  })
}
